export function revenueClient() {
  const $=id=>document.getElementById(id), esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,c)=>typeof v==='number'&&Number.isFinite(v)?`${c||''} ${v.toFixed(2)}`:'—';
  const stamp=v=>v?new Date(v).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'확인 기록 없음';
  const labels={commission_earned:'커미션',commission_pending:'미지급 보상',reward_paid:'보상 지급 상태',available:'출금 가능',withdrawn:'출금 처리',payout_paid:'지급 보고서',declined:'거절 보상'};
  let data;
  function render(){
    if(!data)return;
    $('checked').textContent=`조회 ${stamp(data.generated_at)} KST`;
    $('coverage').textContent=`관리 대상 ${data.program_count}개 프로그램 · ${data.account_count}개 계정 묶음 · 실시간 ${data.connected_accounts}개 / 포털 확인 ${data.snapshot_accounts}개 / 로그인 단계 ${data.blocked_accounts}개`;
    $('totals').innerHTML=['commission_earned','available','payout_paid'].map(key=>{const t=data.totals[key],parts=Object.entries(t.by_currency).map(([c,n])=>fmt(n,c));return `<article><span>${esc(labels[key])} · 확인된 계정 소계</span><strong>${parts.map(esc).join('<br>')||'집계 가능한 기록 없음'}</strong><small>${t.checked_accounts} / ${t.total_accounts} 계정 포함${t.complete?' · 전체 확인':' · 나머지는 아래에서 확인'}</small></article>`}).join('');
    $('definition').textContent=data.definitions.totals;
    const q=$('query').value.toLowerCase(), status=$('status').value;
    const rows=data.accounts.filter(a=>`${a.name} ${a.network} ${a.programs.join(' ')}`.toLowerCase().includes(q) && (status==='all'||(status==='open'?!a.complete:a.complete)));
    $('rows').innerHTML=rows.map(a=>{
      const evidence=(a.evidence||[]).map(e=>`<li><b>${esc(e.tool)}</b> · ${esc(e.observed_window || stamp(e.checked_at))}<br>${esc(e.period)}<br>${Object.entries(e.metrics||{}).filter(([,v])=>typeof v==='number').map(([k,v])=>`${esc(({outbound_clicks:'클릭',signups_referrals:'가입',trials:'체험',paid_customers:'유료 고객',gross_sales_revenue:'대시보드 매출',commission_earned:'커미션',commission_pending:'미지급 보상',payout_paid:'지급액',payout_pending:'미지급 잔액',network_reported_conversions:'포털 전환 수',earnings_today:'오늘 수익',network_reported_balance:'포털 잔액',action_earnings:'행동 수익',payout_count:'지급 건수',reward_paid:'보상 paid'})[k]||k)}: ${esc(k!=='payout_count'&&(k.includes('commission')||k.includes('payout')||['gross_sales_revenue','earnings_today','network_reported_balance','action_earnings','reward_paid'].includes(k))?fmt(v,e.currency):v)}`).join(' · ')}<small>${esc(e.source)} · ${esc(e.evidence_id)}</small></li>`).join('');
      const state=a.connection==='connected'?(a.complete?'조회 완료':'범위 점검'):a.connection==='verified_snapshot'?'확인 시점 기록':a.connection==='blocked'?'로그인 단계 필요':a.connection==='error'?'연결 오류':evidence?'과거 근거 보유':'보고서 연결 필요';
      let portal='';try{const u=new URL(a.portal_url);if(u.protocol==='https:'&&!u.username&&!u.password)portal=`<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">기존 포털 열기 ↗</a>`;}catch{}
      return `<tr><td><b>${esc(a.name)}</b><small>${esc(a.network)} · ${a.programs.length}개 프로그램</small><details><summary>포함 프로그램·근거 ${a.evidence?.length||0}건</summary><p>${esc(a.programs.join(', '))}</p><ul>${evidence||'<li>숫자가 기재된 보고서가 아직 연결되지 않았습니다.</li>'}</ul></details></td><td><span class="pill ${a.complete?'ok':''}">${esc(state)}</span><small>${esc(a.observed_window || stamp(a.checked_at))}</small><small>${esc(a.period==='lifetime'?'계정 누적':a.period)}</small></td>${['commission_earned','commission_pending','available','withdrawn','payout_paid'].map(k=>`<td>${esc(fmt(a.metrics?.[k],a.currency))}</td>`).join('')}<td>${esc(a.action)}<small>${portal}</small>${a.coverage?`<details><summary>조회 범위</summary><p>보상 전체: ${a.coverage.rewardsComplete?'예':'아니오'} · 지급 전체: ${a.coverage.payouts?.complete?'예':'아니오'}</p><p>보상 paid: ${esc(fmt(a.metrics?.reward_paid,a.currency))} · 거절 보상: ${esc(fmt(a.metrics?.declined,a.currency))}</p></details>`:''}</td></tr>`;
    }).join('')||'<tr><td colspan="8">검색 결과 없음</td></tr>';
    $('count').textContent=`${rows.length} / ${data.account_count} 계정 표시`;
    const d=data.direct_sales;
    $('direct').innerHTML=d.connection!=='connected'?'<p>기존 결제 장부를 읽지 못했습니다.</p>':d.empty?'<strong>결제 장부 0건</strong><p>기존 COSHUMA 주문 기록을 조회했습니다.</p>':d.currency_totals.map(x=>`<p>${esc(x.currency)} · 유효 결제 ${esc(x.paid_orders)}건 / ${esc(fmt(x.paid_amount,x.currency))} · 환불 ${esc(fmt(x.refunded_amount,x.currency))}</p>`).join('');
    $('directNote').textContent=d.note;
  }
  async function refresh(){
    $('refresh').disabled=true;$('error').textContent='';
    try {const r=await fetch('/ops/revenue-summary.json',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);data=await r.json();render();}
    catch(e){$('error').textContent=`조회 실패 (${e.message}). 로그인 상태를 확인하고 다시 조회하세요. 표시된 이전 값이 있으면 그 확인 시점을 기준으로 읽어주세요.`;}
    finally{$('refresh').disabled=false;}
  }
  $('query').oninput=render;$('status').onchange=render;$('refresh').onclick=refresh;
  $('export').onclick=()=>{if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='coshuma-revenue-summary.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  refresh();
}

export function revenuePage(){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>COSHUMA 전체 수익</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f5f9;color:#18273e;font:15px/1.6 system-ui,-apple-system,sans-serif}main{max-width:1500px;margin:auto;padding:30px}header{display:flex;justify-content:space-between;align-items:center;gap:24px;margin-bottom:25px}.eyebrow{letter-spacing:.16em;font-size:12px;color:#4265ba;font-weight:700}h1{font-size:32px;margin:7px 0}h2{font-size:20px;margin:0 0 10px}p{margin:5px 0}a{color:#285ac2}nav,.controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap}button,select,input,nav a{font:inherit;padding:10px 14px;border:1px solid #cbd5e4;border-radius:8px;background:white;color:#263b59}button{cursor:pointer}button:disabled{opacity:.5}nav a{text-decoration:none}#refresh{background:#315dde;color:white;border-color:#315dde}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:22px 0 12px}article,.panel{background:white;border:1px solid #dde4ef;border-radius:14px;padding:22px}.cards strong{display:block;font-size:30px;margin:14px 0 8px;font-variant-numeric:tabular-nums}small{display:block;color:#65738a;font-size:12px;margin-top:6px}#definition{color:#607087;font-size:13px;margin-bottom:25px}.controls{margin:20px 0}input{min-width:240px;flex:1}label{font-size:13px}.tablewrap{overflow:auto;border:1px solid #dde4ef;border-radius:12px;background:white}table{width:100%;border-collapse:collapse;font-size:13px}th{text-align:left;background:#edf2fa;color:#506179;white-space:nowrap}th,td{padding:15px 12px;border-bottom:1px solid #e5eaf2;vertical-align:top}td:nth-child(n+3):nth-child(-n+7){white-space:nowrap;font-variant-numeric:tabular-nums}td:first-child{min-width:210px}td:last-child{min-width:200px}.pill{display:inline-block;background:#fff1d6;color:#795400;padding:3px 8px;border-radius:12px;font-size:12px}.pill.ok{background:#e0f4ed;color:#096442}details{margin-top:9px}summary{cursor:pointer;color:#436188;font-size:12px}li{margin:12px 0;overflow-wrap:anywhere}ul{padding-left:17px}.panel{margin-top:24px}#error{color:#a32727;font-weight:600}footer{font-size:12px;color:#607087;margin-top:24px}button:focus-visible,a:focus-visible,input:focus,select:focus{outline:3px solid #9bb5fd;outline-offset:2px}@media(max-width:800px){main{padding:16px}header{display:block}.cards{grid-template-columns:1fr}.cards strong{font-size:27px}nav{margin-top:18px}.tablewrap{max-width:100%}h1{font-size:27px}}
</style></head><body><main><header><div><div class="eyebrow">COSHUMA / REVENUE</div><h1>전체 수익 확인</h1><p id="coverage">계정 목록과 수익을 불러오는 중…</p><small id="checked"></small></div><nav><a href="/ops/traffic-revenue.html">방문·클릭 분석</a><button id="export">집계 내려받기</button><button id="refresh">수익 새로고침</button></nav></header><p role="alert" id="error"></p><section class="cards" id="totals" aria-live="polite"></section><p id="definition"></p><section><h2>모든 수익 계정</h2><p>PartnerStack·사이트 결제는 새로고침으로 조회합니다. 기타 포털은 표시된 확인 시점의 기록입니다. 같은 계정은 한 번만 집계합니다.</p><div class="controls"><label for="query">프로그램 검색</label><input id="query" type="search" placeholder="도구 또는 네트워크 이름"><label for="status">보기</label><select id="status"><option value="all">전체 계정</option><option value="open">확인할 계정</option><option value="checked">조회 완료</option></select><span id="count"></span></div><div class="tablewrap"><table><thead><tr><th>계정·프로그램</th><th>상태·확인 시점</th><th>커미션</th><th>미지급 보상</th><th>출금 가능</th><th>출금 처리</th><th>지급 보고서</th><th>다음 확인 방법</th></tr></thead><tbody id="rows"><tr><td colspan="8">불러오는 중…</td></tr></tbody></table></div></section><section class="panel"><h2>사이트 직접 결제</h2><div id="direct">기존 주문 기록 조회 중…</div><small id="directNote"></small></section><footer>금액 — 는 해당 항목 자료 없음입니다. 과거 확인액은 근거를 펼쳐 확인하세요. 커미션·미지급·출금액은 겹치는 단계이므로 서로 더하지 않습니다. 소유자 인증 · 캐시 및 검색 노출 차단.</footer></main><script>const __name=fn=>fn;(${revenueClient.toString()})();</script></body></html>`;}
