#!/usr/bin/env python3
"""Run the COSHUMA Shorts pipeline through render + quality gate.

Default behavior is a safe dry production run: generate evidence-bounded copy,
render an MP4, quality-gate it, and record `ready` in the manifest. Nothing is
uploaded unless --upload-private is explicitly supplied and OAuth environment
variables are available.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import generate_metadata
import generate_script
import quality_gate
import render_short

ROOT = Path(__file__).resolve().parents[2]
MANIFEST_JSON = ROOT / "data" / "youtube_shorts_manifest.json"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def upsert_ready(script: dict, metadata: dict, rendered: dict, report: dict) -> None:
    manifest = json.loads(MANIFEST_JSON.read_text(encoding="utf-8"))
    campaign = script["campaign_slug"]
    entries = manifest.setdefault("entries", [])
    matches = [e for e in entries if e.get("campaign_slug") == campaign]
    if len(matches) > 1:
        raise RuntimeError(f"Duplicate manifest campaign_slug: {campaign}")
    entry = matches[0] if matches else {}
    if not matches:
        entries.append(entry)
    entry.update({
        "content_slug": campaign,
        "source_page": script["source_page"],
        "affiliate_target": script["tool_id"],
        "campaign_slug": campaign,
        "coshuma_url": metadata["coshuma_url"],
        "title": metadata["title"],
        "video_file_name": Path(rendered["output"]).name,
        "video_sha256": sha256_file(Path(rendered["output"])),
        "video_duration_seconds": rendered["duration_seconds"],
        "resolution": rendered["resolution"],
        "script_hash": script["script_hash"],
        "status": "ready",
        "quality_gate": report,
        "evidence": script.get("evidence"),
        "ga4": {"source": "youtube", "medium": "shorts", "campaign": campaign},
        "provenance": "Generated by scripts/youtube_shorts/run_pipeline.py; not uploaded until OAuth/private-upload validation succeeds."
    })
    manifest["entries"] = entries
    MANIFEST_JSON.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def run(tool_id: str, upload_private: bool = False) -> dict:
    script = generate_script.generate(tool_id)
    tool = generate_metadata.load_tool(tool_id)
    coshuma_url = generate_metadata.build_coshuma_url(script["source_page"], script["campaign_slug"])
    title = generate_metadata.build_title(tool, hook=script["hook"].rstrip("."))
    description = generate_metadata.build_description(
        tool,
        coshuma_url,
        script["hook"],
        affiliate_url=tool.get("affiliate_url"),
        include_direct_affiliate_link=False,
        extra_hashtags=script.get("hashtags", []),
    )
    metadata = {
        "title": title,
        "description": description,
        "coshuma_url": coshuma_url,
        "campaign_slug": script["campaign_slug"],
    }

    rendered = render_short.render(tool_id)
    report = quality_gate.run_quality_gate(
        rendered["output"],
        metadata["coshuma_url"],
        metadata["title"],
        metadata["description"],
        affiliate_target=script["tool_id"],
        campaign_slug=script["campaign_slug"],
        narration=script.get("narration"),
    )
    if not report["passed"]:
        raise RuntimeError("Shorts quality gate failed: " + "; ".join(report["failures"]))
    upsert_ready(script, metadata, rendered, report)

    result = {"script": script, "metadata": metadata, "render": rendered, "quality_gate": report}
    if upload_private:
        import upload_youtube
        video_id = upload_youtube.upload(
            Path(rendered["output"]), metadata["title"], metadata["description"], privacy="private"
        )
        upload_youtube.record_manifest(script["campaign_slug"], video_id, "private")
        result["youtube_video_id"] = video_id
        result["youtube_privacy"] = "private"
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tool_id")
    parser.add_argument("--upload-private", action="store_true")
    args = parser.parse_args()
    print(json.dumps(run(args.tool_id, args.upload_private), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
