import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {deflateSync} from 'node:zlib';
import {createHmac} from 'node:crypto';
import {catalog,quote,imageInfo,validateMaterials,sha256} from '../src/ad-sales-domain.js';
import {handleImageAdRequest,handleImageAdWebhook} from '../src/ad-sales.js';
const origin='https://coshuma.com',api='https://test.workers.dev';
class D1 {
 constructor(){this.db=new DatabaseSync(':memory:');for(const f of ['0004_sponsorship_sales.sql','0005_image_ad_sales.sql'])this.db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));}
 prepare(sql){const db=this.db;function make(args=[]){return {bind:(...a)=>make(a.map(v=>Array.isArray(v)?Buffer.from(v):v)),first:async()=>db.prepare(sql).get(...args)||null,all:async()=>({results:db.prepare(sql).all(...args)}),run:async()=>({meta:db.prepare(sql).run(...args)}),exec:()=>({results:db.prepare(sql).all(...args)})};}return make();}
 async batch(stmts){this.db.exec('BEGIN');try{const v=[];for(const s of stmts)v.push(s.exec());this.db.exec('COMMIT');return v;}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
function crc(b){let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function png(w,h){const chunk=(type,data)=>{const t=Buffer.from(type),n=Buffer.alloc(4),z=Buffer.alloc(4);n.writeUInt32BE(data.length);z.writeUInt32BE(crc(Buffer.concat([t,data])));return Buffer.concat([n,t,data,z]);};const ih=Buffer.alloc(13);ih.writeUInt32BE(w,0);ih.writeUInt32BE(h,4);ih[8]=8;ih[9]=6;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ih),chunk('IDAT',deflateSync(Buffer.alloc((w*4+1)*h))),chunk('IEND',Buffer.alloc(0))]);}
const future=()=>new Date(Date.now()+5*86400000).toISOString().slice(0,10);
function material(id='tool-primary',rotation){const p=catalog.positions.find(p=>p.id===id)||catalog.bundles.find(p=>p.id===id),slots=p.fixed?[...p.fixed,...(p.chooseOne.length?[rotation]:[])]:[p.id];return {productId:id,durationDays:30,startDate:future(),...(rotation?{rotation}:{}),advertiser:'COSHUMA test',product:'Test product',email:'qa@example.com',billingName:'QA Company',claims:'Test fixture, not a live advertiser claim.',rightsConfirmed:true,termsAccepted:true,logo:{base64:png(400,400).toString('base64')},creatives:slots.map(slot=>{const p=catalog.positions.find(p=>p.id===slot);return {slot,title:'A relevant software product',body:'Compare software features and choose an appropriate product.',button:'View product',alt:'A static software product illustration',url:'https://example.com/product',image:{base64:png(p.width,p.height).toString('base64')}};})};}
async function setup(){const db=new D1(),secret='TEST_ONLY_OWNER_HASH_NOT_A_REAL_SECRET',env={ORDERS:db,ALLOWED_ORIGIN:origin,IMAGE_AD_INTAKE_ENABLED:'true',IMAGE_AD_CHECKOUT_ENABLED:'true',PAYPAL_ENVIRONMENT:'live',PAYPAL_CLIENT_ID:'TEST_CLIENT',PAYPAL_CLIENT_SECRET:'TEST_SECRET',PAYPAL_MERCHANT_ID:'TEST_MERCHANT',PAYPAL_WEBHOOK_ID:'TEST_WEBHOOK',OPS_PASSWORD_SHA256:secret};await db.prepare('INSERT INTO ad_sales_readiness VALUES(1,?,?)').bind(new Date().toISOString(),JSON.stringify({good:true})).run();const expires=Math.floor(Date.now()/1000)+3600,sig=createHmac('sha256',secret).update('support@coshuma.com:/ops:'+expires).digest('hex');return {db,env,cookie:'coshuma_ops='+expires+'.'+sig};}
async function call(env,path,body,token,cookie){const admin=path.startsWith('/ops/'),req=new Request(api+(admin?path:'/v2/advertising'+path),{method:body===undefined?'GET':'POST',headers:{origin:admin?api:origin,...(body===undefined?{}:{'content-type':'application/json'}),...(token?{authorization:'Bearer '+token}:{}),...(cookie?{cookie}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const r=await handleImageAdRequest(req,env);return {status:r.status,data:await r.json()};}
const submit=(env,m=material())=>call(env,'/applications',m);
const approve=(env,id,cookie)=>call(env,'/ops/image-ads/applications/'+id+'/review',{decision:'approve',notes:'Every test image decoded, claims and material rights checked.',assetsDecoded:true},null,cookie);
test('catalogue prices and exact bundle scope, dates and server-owned quotes',()=>{assert.equal(catalog.positions.length,8);assert.equal(catalog.bundles.length,3);assert.equal(quote(material('sales-crm-duo')).amount,'129.00');assert.deepEqual(quote(material('discovery-mix','guide-rotation')).slots,['buyer-hub-fixed','guide-rotation']);assert.throws(()=>quote({...material(),amount:'0.01'}));assert.throws(()=>quote({...material(),durationDays:9}));assert.throws(()=>quote({...material(),startDate:'2026-02-31'}));assert.throws(()=>quote({...material('discovery-mix','tool-rotation'),rotation:'unknown'}));});
test('image sizes, real static structure, logo alpha and per-file limits',async()=>{assert.equal(imageInfo(png(600,600)).width,600);assert.equal((await validateMaterials(material())).assets.length,2);const m=material();m.logo.base64=png(10,10).toString('base64');await assert.rejects(validateMaterials(m));const m2=material();m2.creatives[0].image.base64=Buffer.alloc(300001).toString('base64');await assert.rejects(validateMaterials(m2));assert.throws(()=>imageInfo(Buffer.from('<svg onload="alert(1)"/>')));});
test('intake gives an actual receipt; private images and price remain protected',async()=>{const {db,env}=await setup();const r=await submit(env);assert.equal(r.status,201,JSON.stringify(r));assert.equal(r.data.state,'submitted');const a=db.db.prepare('SELECT * FROM ad_sales_applications').get();assert.notEqual(a.token_hash,r.data.accessToken);assert.equal(JSON.parse(a.quote_json).amount,'49.00');const image=db.db.prepare('SELECT id FROM ad_sales_assets LIMIT 1').get();assert.equal((await call(env,'/assets/'+image.id)).status,404);assert.equal((await call(env,'/applications/'+a.id)).status,401);assert.equal((await call(env,'/applications/'+a.id,undefined,r.data.accessToken)).status,200);assert.equal((await call(env,'/applications/'+a.id+'/order',{},r.data.accessToken)).status,409);const closed=await submit({...env,IMAGE_AD_INTAKE_ENABLED:'false'});assert.equal(closed.status,503);});
function provider(){const orders=new Map(),captures=new Map();let serial=0,captureCalls=0;return {get captureCalls(){return captureCalls;},fetch:async(url,opt={})=>{url=String(url);const path=new URL(url).pathname;let value;if(path==='/v1/oauth2/token')value={access_token:'TEST_TOKEN'};else if(path==='/v2/checkout/orders'&&opt.method==='POST'){const payload=JSON.parse(opt.body),id='TEST_ORDER_'+(++serial);value={...payload,id,status:'CREATED'};orders.set(id,value);}else if(/^\/v2\/checkout\/orders\//.test(path)){const id=path.split('/')[4];const o=orders.get(id);if(!o)throw Error('Unknown mock order');if(path.endsWith('/capture')){captureCalls++;o.status='COMPLETED';const c={id:'TEST_CAPTURE_'+id,status:'COMPLETED',amount:o.purchase_units[0].amount,payee:o.purchase_units[0].payee,supplementary_data:{related_ids:{order_id:id}},custom_id:o.purchase_units[0].custom_id,invoice_id:o.purchase_units[0].invoice_id};captures.set(c.id,c);o.purchase_units[0].payments={captures:[c]};}value=o;}else if(path.startsWith('/v2/payments/captures/'))value=captures.get(path.split('/').pop());else throw Error('Unexpected external request in test: '+path);return new Response(JSON.stringify(value),{status:200,headers:{'content-type':'application/json'}});}};}
test('review authentication and atomic rotating capacity of three; bundle rollback',async()=>{const {db,env,cookie}=await setup(),mock=provider(),original=globalThis.fetch;globalThis.fetch=mock.fetch;try{for(let i=0;i<4;i++){const r=await submit(env,material('tool-rotation'));if(i===3){assert.equal(r.status,409);continue;}assert.equal(r.status,201);assert.equal((await approve(env,r.data.id)).status,401);assert.equal((await approve(env,r.data.id,cookie)).status,200);const order=await call(env,'/applications/'+r.data.id+'/order',{},r.data.accessToken);assert.equal(order.status,i<3?200:409,JSON.stringify(order));}assert.equal(db.db.prepare('SELECT count(*) n FROM ad_sales_allocations').get().n,3);const b=await submit(env,material('discovery-mix','tool-rotation'));assert.equal(b.status,409);assert.equal(mock.captureCalls,0);}finally{globalThis.fetch=original;}});
test('verified matching payment schedules both positions, retries do not recharge, refund stops both',async()=>{const {db,env,cookie}=await setup(),mock=provider(),original=globalThis.fetch;globalThis.fetch=mock.fetch;try{const r=await submit(env,material('sales-crm-duo'));assert.equal(r.status,201);assert.equal((await approve(env,r.data.id,cookie)).status,200);const o=await call(env,'/applications/'+r.data.id+'/order',{},r.data.accessToken);assert.equal(o.status,200,JSON.stringify(o));assert.equal(db.db.prepare('SELECT count(*) n FROM ad_sales_allocations').get().n,2);const wrong=await call(env,'/applications/'+r.data.id+'/capture',{orderId:'OTHER_ORDER'},r.data.accessToken);assert.equal(wrong.status,409);assert.equal(mock.captureCalls,0);const paid=await call(env,'/applications/'+r.data.id+'/capture',{orderId:o.data.orderId},r.data.accessToken);assert.equal(paid.status,200,JSON.stringify(paid));assert.equal(paid.data.state,'scheduled');assert.equal(paid.data.paymentVerified,true);const again=await call(env,'/applications/'+r.data.id+'/capture',{orderId:o.data.orderId},r.data.accessToken);assert.equal(again.status,200);assert.equal(mock.captureCalls,1);const a=db.db.prepare('SELECT * FROM ad_sales_applications').get();await handleImageAdWebhook({event_type:'PAYMENT.CAPTURE.REFUNDED'},env,{relatedOrderId:a.provider_order_id,captureIds:[a.capture_id]});assert.equal((await call(env,'/applications/'+r.data.id,undefined,r.data.accessToken)).data.state,'refunded');assert.equal((await call(env,'/applications/'+r.data.id+'/capture',{orderId:o.data.orderId},r.data.accessToken)).status,409);assert.equal(mock.captureCalls,1);}finally{globalThis.fetch=original;}});
test('transaction rolls back a bundle when its second allocation becomes unavailable',async()=>{const {db,env,cookie}=await setup(),mock=provider(),original=globalThis.fetch;globalThis.fetch=mock.fetch;try{const bundle=await submit(env,material('sales-crm-duo'));await approve(env,bundle.data.id,cookie);const fixed=await submit(env,material('buyer-intent-top'));await approve(env,fixed.data.id,cookie);assert.equal((await call(env,'/applications/'+fixed.data.id+'/order',{},fixed.data.accessToken)).status,200);assert.equal((await call(env,'/applications/'+bundle.data.id+'/order',{},bundle.data.accessToken)).status,409);assert.equal(db.db.prepare('SELECT count(*) n FROM ad_sales_allocations WHERE application_id=?').get(bundle.data.id).n,0);assert.equal(mock.captureCalls,0);}finally{globalThis.fetch=original;}});
