import fs from './affiliate_state_fs.mjs';
import './ensure_justuno_fastlane.mjs';

const checkedAt='2026-10-07T17:05:08+09:00';
const optimonk={
  id:'optimonk',name:'OptiMonk',category:'dev_coding',category_display:'Coding & Dev Tools',
  description:'Conversion-rate optimization platform for popups, embedded campaigns, targeting, personalization and experimentation.',
  affiliate_url:null,
  pricing:'Free plan at $0 for up to 10,000 pageviews/month on one domain with unlimited campaigns and all features; paid tiers scale by traffic and billing period',
  key_features:['Popup and embedded campaigns','Behavioral targeting','Personalization','A/B and conversion experimentation','Ecommerce conversion optimization'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=optimonk.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://www.optimonk.com/',pricing_source_url:'https://www.optimonk.com/pricing',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on plan and traffic',
  evidence_source_type:'official_pricing_partner_and_help_pages',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://www.optimonk.com/partners',
  affiliate_verified:false,affiliate_status:'application_available_account_required',affiliate_source_url:'https://www.optimonk.com/partners',affiliate_workflow_url:'mailto:partnership@optimonk.com',affiliate_status_checked_at:checkedAt,application_state:'not_submitted',
  affiliate_evidence_markers:[
    "OptiMonk Partnership Manager confirmed by Gmail message 1a0b67cafbf349f that independent publishers can use a classic affiliate model with 20% commission for two years on referred paying customers.",
    "OptiMonk Partnership Manager confirmed by Gmail message 1a115654c5759cfa that enrollment requires creating a free OptiMonk product account, then sending the registered email so the supplier can upgrade it to an affiliate account.",
    "The supplier says a unique customer affiliate link is issued only after that upgrade; no generic homepage, signup, login, onboarding or dashboard URL is a verified customer tracking URL.",
    "The supplier says commissions, refunds and corrections appear in the balance; payouts can be requested one at a time from $50, require an invoice requested by email, and are paid by bank transfer.",
    "COSHUMA has not created the required product account, completed enrollment, received an account-specific tracking URL, or verified any click, signup, paid customer, commission, payout or revenue.",
    "No duplicate reply is required because the supplier directly answered the enrollment and payout questions."
],
  affiliate_next_action:"Reuse an existing authenticated COSHUMA-owned OptiMonk account if later evidenced. Otherwise keep enrollment on hold because a new affiliate product account is required. After supplier upgrade, recover and verify only the issued customer-facing tracking URL before any affiliate CTA."
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===optimonk.id);if(existing)Object.assign(existing,optimonk);else tools.push(optimonk);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}

const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-10-07';outreach.programs||={};outreach.programs.optimonk={status:'application_available_account_required',tracking_url:null,application_state:'not_submitted',account:'support@coshuma.com',official_program_url:'https://www.optimonk.com/partners',workflow_url:'mailto:partnership@optimonk.com',github_issue:491,checked_at:checkedAt,outreach_message_id:'1a0fee78f87e9e57',vendor_reply_message_id:'1a115654c5759cfa',note:'Supplier confirmed publisher eligibility and the 20% for two years model, but enrollment requires a free OptiMonk product account before the supplier upgrades it and issues the unique link. No account, application, approval or tracking URL is verified; no duplicate reply is needed.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);

const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));let item=queue.find(i=>i.tool_id==='optimonk'||String(i.id||'').startsWith('optimonk-affiliate-'));const patch={tool_id:'optimonk',priority:'high',status:'application_available_account_required',affiliate_status:'application_available_account_required',application_state:'not_submitted',cost:0,exact_tracking_url:null,user_action_required:false,blocker:'Supplier-confirmed enrollment requires a free OptiMonk product account before affiliate upgrade and unique-link issuance; no existing COSHUMA-owned product account is evidenced.',reason:'Direct supplier reply 1a115654c5759cfa resolves publisher eligibility and payout questions but does not prove account creation, enrollment, approval or a customer tracking URL.',official_program_url:'https://www.optimonk.com/partners',next_action:"Reuse an existing authenticated COSHUMA-owned OptiMonk account if later evidenced. Otherwise keep enrollment on hold because a new affiliate product account is required. After supplier upgrade, recover and verify only the issued customer-facing tracking URL before any affiliate CTA.",do_not_reapply:true,verified_at:checkedAt,github_issue:491,outreach_message_id:'1a0fee78f87e9e57',vendor_reply_message_id:'1a115654c5759cfa'};if(item)Object.assign(item,patch);else queue.push({id:'optimonk-affiliate-application-20260914',...patch});fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);

const urls=['https://coshuma.com/tool/optimonk.html','https://coshuma.com/best/optimonk-free-plan-pricing.html','https://coshuma.com/compare/optimonk-vs-popupsmart.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);

const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/optimonk.html'))llms+='\n## OptiMonk buyer guides\n\n- https://coshuma.com/tool/optimonk.html — OptiMonk free plan, CRO workflow and product-fit buyer guide\n- https://coshuma.com/best/optimonk-free-plan-pricing.html — OptiMonk free-plan and upgrade decision guide\n- https://coshuma.com/compare/optimonk-vs-popupsmart.html — OptiMonk vs Popupsmart onsite-conversion comparison\n';fs.writeFileSync(llmsPath,llms);

const hubBlock=`\n<section data-optimonk-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-5"><div class="text-xs uppercase tracking-widest text-emerald-300 font-bold">Conversion optimization</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-emerald-300" href="/best/optimonk-free-plan-pricing.html">OptiMonk free plan & pricing</a> · <a class="font-bold text-white hover:text-emerald-300" href="/tool/optimonk.html">OptiMonk buyer guide</a> · <a class="font-bold text-white hover:text-emerald-300" href="/compare/optimonk-vs-popupsmart.html">OptiMonk vs Popupsmart</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-optimonk-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}

const popupsmartPath='public/tool/popupsmart.html';if(fs.existsSync(popupsmartPath)){let html=fs.readFileSync(popupsmartPath,'utf8');if(!html.includes('data-optimonk-related="2026-09-14"')){const links=`<section data-optimonk-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-6"><h2 class="text-xl font-black text-white">Compare another free-entry CRO option</h2><p class="mt-2 text-sm text-slate-300">OptiMonk currently offers a larger free pageview allowance and positions itself as a broader CRO and personalization platform.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/optimonk-vs-popupsmart.html" class="rounded-xl bg-emerald-600 px-5 py-3 text-center text-sm font-black text-white">OptiMonk vs Popupsmart →</a><a href="/tool/optimonk.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">OptiMonk buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(popupsmartPath,html);}}
console.log('OptiMonk fast-lane state, discoverability and vendor eligibility inquiry state ensured');
