import fs from './affiliate_state_fs.mjs';
import './ensure_creatify_fastlane.mjs';

const checkedAt='2026-09-14T07:38:00+09:00';
const lifecycleCheckedAt='2026-10-07T11:22:00+09:00';
const poptin={
  id:'poptin',name:'Poptin',category:'dev_coding',category_display:'Coding & Dev Tools',
  description:'Popup, form and onsite conversion platform with targeting, triggers, A/B testing, coupons, integrations and built-in email marketing automation.',
  affiliate_url:null,
  pricing:'Free Forever for up to 1,000 visitors/month; Basic, Pro and Agency paid tiers available with monthly/annual billing options',
  key_features:['Popup and form builder','Exit-intent and behavior triggers','Advanced targeting rules','A/B testing and campaign analytics','Email campaigns, automation and 70+ native integrations'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=poptin.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://www.poptin.com/',pricing_source_url:'https://www.poptin.com/pricing/',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on plan',
  evidence_source_type:'official_pricing_and_affiliate_pages',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://www.poptin.com/affiliate/',
  affiliate_verified:false,affiliate_status:'browser_required_legal_program_consent',affiliate_source_url:'https://www.poptin.com/affiliate/',affiliate_workflow_url:'https://app.popt.in/',affiliate_status_checked_at:lifecycleCheckedAt,application_state:'not_submitted',
  affiliate_evidence_markers:[
    'Official Poptin affiliate page states the program is open to all and registration is free.',
    'Official Poptin terms require signup and Terms of Service acceptance before access to the affiliate control panel.',
    'Official program says the unique affiliate link is provided in the authenticated control panel.',
    'Official current program advertises a 90-day cookie window and lifetime 25% monthly commission for each new paying member recruited.',
    'Official pricing and affiliate pages advertise a Free Forever account for 1,000 visitors per month and no credit card required.',
    'GitHub search found no pre-existing COSHUMA Poptin record before this fast-lane cycle.',
    'support@coshuma.com Gmail in:anywhere search found no prior Poptin application, approval, rejection, tracking-link, commission or payout message.',
    'Exact account-specific customer referral URL is unknown; app/dashboard/login/onboarding/homepage URLs must not be used as affiliate CTAs.',
    'GitHub issue #485 tracks the free account registration and exact control-panel referral URL recovery.'
  ],
  affiliate_next_action:'Hold at legal consent. After the account holder accepts the official Terms of Service through a supported normal flow, check for an existing COSHUMA account before any registration, then recover and validate only the unique vendor-issued customer referral URL from the authenticated control panel. Stop for CAPTCHA, OTP, forced identity verification or payment approval.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===poptin.id);if(existing)Object.assign(existing,poptin);else tools.push(poptin);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}
const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.poptin={status:'browser_required_legal_program_consent',tracking_url:null,application_state:'not_submitted',account:'support@coshuma.com',official_program_url:'https://www.poptin.com/affiliate/',workflow_url:'https://app.popt.in/',github_issue:485,checked_at:lifecycleCheckedAt,note:'Official Poptin terms require signup and Terms of Service acceptance before access to the affiliate control panel. No existing COSHUMA Poptin application or account-specific referral URL was found in GitHub/Gmail. Do not use the app URL as a customer CTA.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);
const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));const poptinQueue={id:'poptin-affiliate-2026-09-14',tool_id:'poptin',priority:'high',status:'browser_required_legal_program_consent',affiliate_status:'browser_required_legal_program_consent',application_state:'not_submitted',cost:0,exact_tracking_url:null,user_action_required:true,blocker:'Official Poptin signup requires Terms of Service acceptance before access to the authenticated affiliate control panel.',reason:'Repository and Gmail duplicate checks are clear, but legal consent and the account/control-panel step are not complete.',next_action:'Hold at legal consent. After the account holder accepts the official Terms of Service through a supported normal flow, check for an existing COSHUMA account before any registration and recover only the exact vendor-issued referral URL. Stop for CAPTCHA, OTP, forced identity verification or payment approval.',do_not_reapply:true,verified_at:lifecycleCheckedAt,github_issue:485};const existingPoptinQueue=queue.find(i=>i.tool_id==='poptin'||String(i.id||'').startsWith('poptin-'));if(existingPoptinQueue)Object.assign(existingPoptinQueue,poptinQueue);else queue.push(poptinQueue);fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);
const urls=['https://coshuma.com/tool/poptin.html','https://coshuma.com/best/poptin-free-plan-pricing.html','https://coshuma.com/compare/poptin-vs-popupsmart.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);
const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/poptin.html'))llms+='\n## Poptin buyer guides\n\n- https://coshuma.com/tool/poptin.html — Poptin free plan, pricing and conversion-tool buyer guide\n- https://coshuma.com/best/poptin-free-plan-pricing.html — Poptin free plan and paid-plan decision guide\n- https://coshuma.com/compare/poptin-vs-popupsmart.html — Poptin vs Popupsmart popup and onsite conversion comparison\n';fs.writeFileSync(llmsPath,llms);
const hubBlock=`\n<section data-poptin-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-purple-500/25 bg-purple-500/5 p-5"><div class="text-xs uppercase tracking-widest text-purple-300 font-bold">Popups & onsite conversion</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-purple-300" href="/best/poptin-free-plan-pricing.html">Poptin free plan & pricing</a> · <a class="font-bold text-white hover:text-purple-300" href="/tool/poptin.html">Poptin buyer guide</a> · <a class="font-bold text-white hover:text-purple-300" href="/compare/poptin-vs-popupsmart.html">Poptin vs Popupsmart</a></p></div></section>\n`;for(const file of ['public/best/index.html','index.html']){let html=fs.readFileSync(file,'utf8');if(!html.includes('data-poptin-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}
console.log('Poptin fast-lane state, browser queue and discoverability ensured');
