import fs from 'node:fs';

const checkedAt='2026-09-14T12:38:00+09:00';
const picreel={
  id:'picreel',name:'Picreel',category:'dev_coding',category_display:'Conversion Optimization',
  description:'Popup and CRO platform for exit offers, lead capture, targeting, A/B testing and onsite campaigns.',
  affiliate_url:null,
  pricing:'$0 Forever Free plan with all premium features up to 5,000 pageviews/month; official product page says no credit card is required to start',
  key_features:['Exit-intent popups','Lead capture forms','Targeting and personalization','A/B testing','Analytics and integrations'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=picreel.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://www.picreel.com/',pricing_source_url:'https://www.picreel.com/pricing/',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'permanent free tier or paid plan',
  evidence_source_type:'official_picreel_and_proprofs_affiliate_pages',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://www.proprofs.com/affiliates/',
  affiliate_verified:false,affiliate_status:'browser_required_legal_program_consent',affiliate_source_url:'https://www.proprofs.com/affiliates/',affiliate_workflow_url:'https://proprofs.firstpromoter.com/',affiliate_status_checked_at:checkedAt,application_state:'not_submitted_legal_consent_required',
  affiliate_evidence_markers:[
    'Official Picreel pricing advertises a $0 Forever Free plan with all premium features up to 5,000 pageviews per month.',
    'Picreel official product page states free entry requires no credit card.',
    'ProProfs Affiliate Program terms explicitly include Picreel.com among covered sites.',
    'Official ProProfs affiliate page says application is free and affiliates use unique portal-issued referral links.',
    'Current public affiliate marketing page advertises a one-time 100% of first-month subscription on monthly-plan referrals and 40% of signup fee on annual-plan referrals, but binding account terms are determined on acceptance or written agreement and shown in the portal.',
    'ProProfs legal terms explicitly say submitting an affiliate application is express acceptance of a legal agreement, so unattended submission is not permitted.',
    'ProProfs terms prohibit multiple affiliate/referral accounts and require exact portal-issued affiliate links; generic homepage, portal and signup URLs are not customer tracking URLs.',
    'Fresh GitHub and support@coshuma.com Gmail checks found no prior Picreel or ProProfs affiliate relationship before this cycle.',
    'Exact account-issued customer referral URL is unknown; clicks, signups, paid customers, commission, payout and revenue remain unknown.',
    'GitHub issue #505 tracks legal-consent-gated enrollment and exact referral-link recovery.'
  ],
  affiliate_next_action:'The account holder must review and accept the ProProfs Affiliate Program terms in the official FirstPromoter application before submitting. Submit only one ProProfs affiliate application if accepted, then recover and verify only the exact portal-issued customer-facing link applicable to Picreel. Stop for CAPTCHA, OTP, additional legal consent, forced identity verification or payment approval.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===picreel.id);if(existing)Object.assign(existing,picreel);else tools.push(picreel);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}
const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.picreel={status:'browser_required_legal_program_consent',tracking_url:null,application_state:'not_submitted_legal_consent_required',account:'support@coshuma.com',official_program_url:'https://www.proprofs.com/affiliates/',workflow_url:'https://proprofs.firstpromoter.com/',github_issue:505,checked_at:checkedAt,note:'Picreel is explicitly covered by ProProfs Affiliate Program terms. Enrollment is free but application submission is express legal agreement acceptance. No application was submitted unattended; exact customer referral URL and all revenue stages remain unknown.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);
const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));if(!queue.some(i=>i.tool_id==='picreel'||String(i.id||'').startsWith('picreel-'))){queue.push({id:'picreel-proprofs-affiliate-2026-09-14',tool_id:'picreel',priority:'high',status:'browser_required_legal_program_consent',affiliate_status:'browser_required_legal_program_consent',application_state:'not_submitted_legal_consent_required',cost:0,exact_tracking_url:null,user_action_required:true,blocker:'Submitting the ProProfs FirstPromoter application is express acceptance of the ProProfs Affiliate Program legal agreement.',reason:'Duplicate checks are clear and Picreel is an explicitly covered ProProfs site, but legal/program consent belongs to the account holder and multiple affiliate accounts are prohibited.',next_action:'Open the official ProProfs FirstPromoter application, review and accept the linked Affiliate Program terms only if the account holder agrees, submit once, then recover only the exact portal-issued customer referral link applicable to Picreel. Stop for CAPTCHA, OTP, additional legal consent, forced identity verification or payment approval.',do_not_reapply:true,verified_at:checkedAt,github_issue:505});}fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);
const urls=['https://coshuma.com/tool/picreel.html','https://coshuma.com/best/picreel-free-plan-pricing.html','https://coshuma.com/compare/picreel-vs-claspo.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);
const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/picreel.html'))llms+='\n## Picreel buyer guides\n\n- https://coshuma.com/tool/picreel.html — Picreel Forever Free popup/CRO buyer guide and pricing and product-fit facts\n- https://coshuma.com/best/picreel-free-plan-pricing.html — Picreel free-plan and upgrade decision guide\n- https://coshuma.com/compare/picreel-vs-claspo.html — Picreel vs Claspo permanent-free popup comparison\n';fs.writeFileSync(llmsPath,llms);
const hubBlock=`\n<section data-picreel-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-orange-500/25 bg-orange-500/5 p-5"><div class="text-xs uppercase tracking-widest text-orange-300 font-bold">Popups & CRO</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-orange-300" href="/best/picreel-free-plan-pricing.html">Picreel free plan & pricing</a> · <a class="font-bold text-white hover:text-orange-300" href="/tool/picreel.html">Picreel buyer guide</a> · <a class="font-bold text-white hover:text-orange-300" href="/compare/picreel-vs-claspo.html">Picreel vs Claspo</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-picreel-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}
const claspoPath='public/tool/claspo.html';if(fs.existsSync(claspoPath)){let html=fs.readFileSync(claspoPath,'utf8');if(!html.includes('data-picreel-related="2026-09-14"')){const links=`<section data-picreel-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-orange-500/25 bg-orange-500/5 p-6"><h2 class="text-xl font-black text-white">Compare another permanent-free popup tool</h2><p class="mt-2 text-sm text-slate-300">Picreel currently publishes a 5K-pageview Forever Free tier, while Claspo's current Free selector shows 3K pageviews. Compare the real editor and targeting workflow before paying.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/picreel-vs-claspo.html" class="rounded-xl bg-orange-600 px-5 py-3 text-center text-sm font-black text-white">Picreel vs Claspo →</a><a href="/tool/picreel.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">Picreel buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(claspoPath,html);}}
console.log('Picreel fast-lane state, legal-consent browser queue and discoverability ensured');
