import fs from 'node:fs';

const checkedAt='2026-09-15T18:00:00+09:00';
const convertflow={
  id:'convertflow',name:'ConvertFlow',category:'dev_coding',category_display:'Coding & Dev Tools',
  description:'Funnel builder for landing pages, lead forms, quizzes, popups, targeted offers, personalization and conversion experiments.',
  affiliate_url:'https://app.convertflow.com/refer?fpr=sangkwon-an-334dcb',
  pricing:'Free signup with no credit card required; current Personal display starts at $29/month monthly or $25/month annual-billing equivalent with up to 10K monthly funnel views; pricing varies by plan and traffic',
  key_features:['Landing-page funnels','Quiz and lead-form funnels','Popup funnels','Targeted offers and personalization','Conversion analytics and experiments'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=convertflow.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://www.convertflow.com/',pricing_source_url:'https://www.convertflow.com/pricing',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on plan and funnel traffic',
  evidence_source_type:'official_pricing_help_center_and_gmail',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',
  affiliate_verified:true,affiliate_status:'approved_tracking',affiliate_source_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',affiliate_workflow_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',affiliate_status_checked_at:checkedAt,application_state:'enrolled_tracking_link_verified',
  affiliate_evidence_markers:[
    'Official ConvertFlow referral-program knowledge base says partners join from a ConvertFlow account, enter a PayPal payout email and receive a unique referral link in the affiliate dashboard.',
    'Current referral documentation states 30% commission on eligible self-service subscription renewals for up to 12 months and that self-referrals are not commissionable.',
    'Official pricing page currently says users can start free without a credit card; current Personal display starts at $29/month monthly or $25/month annual-billing equivalent with up to 10K monthly funnel views.',
    'Fresh GitHub code/open-issue and support@coshuma.com Gmail checks found no pre-existing ConvertFlow application or relationship before this cycle.',
    'ConvertFlow support corrected its earlier guidance on 2026-09-15: the Referral Program is separate from the Pro-only Partner Program, requires no paid plan, and is reached from profile icon → Referrals.',
    'COSHUMA created the single support@coshuma.com account and received the ConvertFlow welcome email on 2026-09-15.',
    'On 2026-09-15 the authenticated support@coshuma.com account reached the free dashboard, completed the separate FirstPromoter referral enrollment, and displayed the account-issued Home Page customer referral URL.',
    'Authenticated FirstPromoter displayed 0 clicks, 0 referrals, 0 customers, $0 total unpaid and $0 total paid at verification time; no signup, sale, commission, payout or revenue is inferred.',
    'PayPal payout method support@coshuma.com was selected and verified by emailed 2FA. W-8BEN tax documentation remains account-owner legal work and is not treated as completed.',
    'Generic homepage, signup, Partners navigation and affiliate dashboard URLs must not be treated as affiliate links.',
    'GitHub issue #497 tracks vendor response, exact enrollment path and future customer referral URL recovery.'
  ],
  affiliate_next_action:'Preserve the exact account-issued Referral Program URL and do not create another account or pursue the separate Pro-only Partner Program for referral tracking. Complete W-8BEN only through account-owner legal review. Recheck clicks, referrals, customers, unpaid and paid commission from the authenticated dashboard without inferring revenue.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===convertflow.id);if(existing)Object.assign(existing,convertflow);else tools.push(convertflow);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}
const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-15';outreach.programs||={};outreach.programs.convertflow={status:'approved_tracking',tracking_url:'https://app.convertflow.com/refer?fpr=sangkwon-an-334dcb',application_state:'enrolled_tracking_link_verified',account:'support@coshuma.com',official_program_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',workflow_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',contact_email:'support@convertflow.com',github_issue:497,checked_at:checkedAt,note:'Authenticated ConvertFlow and FirstPromoter dashboards confirm one support@coshuma.com account, completed Referral Program enrollment, verified PayPal payout method and the exact account-issued referral URL. ConvertFlow support confirmed this is separate from the Pro-only Partner Program and requires no paid plan. Dashboard totals at verification: 0 clicks, 0 referrals, 0 customers, $0 unpaid and $0 paid. W-8BEN remains account-owner legal work. Do not re-enroll or infer revenue.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);
const urls=['https://coshuma.com/tool/convertflow.html','https://coshuma.com/best/convertflow-free-plan-pricing.html','https://coshuma.com/compare/convertflow-vs-unbounce.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);
const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/convertflow.html'))llms+='\n## ConvertFlow buyer guides\n\n- https://coshuma.com/tool/convertflow.html — ConvertFlow free entry, funnel builder, pricing and referral-status buyer guide\n- https://coshuma.com/best/convertflow-free-plan-pricing.html — ConvertFlow free-plan and upgrade decision guide\n- https://coshuma.com/compare/convertflow-vs-unbounce.html — ConvertFlow vs Unbounce funnels and landing-page CRO comparison\n';fs.writeFileSync(llmsPath,llms);
const hubBlock=`\n<section data-convertflow-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-cyan-500/25 bg-cyan-500/5 p-5"><div class="text-xs uppercase tracking-widest text-cyan-300 font-bold">Funnels & CRO</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-cyan-300" href="/best/convertflow-free-plan-pricing.html">ConvertFlow free plan & pricing</a> · <a class="font-bold text-white hover:text-cyan-300" href="/tool/convertflow.html">ConvertFlow buyer guide</a> · <a class="font-bold text-white hover:text-cyan-300" href="/compare/convertflow-vs-unbounce.html">ConvertFlow vs Unbounce</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-convertflow-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}
const unbouncePath='public/tool/unbounce.html';if(fs.existsSync(unbouncePath)){let html=fs.readFileSync(unbouncePath,'utf8');if(!html.includes('data-convertflow-related="2026-09-14"')){const links=`<section data-convertflow-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-cyan-500/25 bg-cyan-500/5 p-6"><h2 class="text-xl font-black text-white">Compare a broader funnel builder</h2><p class="mt-2 text-sm text-slate-300">ConvertFlow currently offers a no-card free starting point for landing pages, forms, quizzes and popups. Compare it with Unbounce when deciding between broader funnel logic and dedicated landing-page CRO.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/convertflow-vs-unbounce.html" class="rounded-xl bg-cyan-600 px-5 py-3 text-center text-sm font-black text-white">ConvertFlow vs Unbounce →</a><a href="/tool/convertflow.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">ConvertFlow buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(unbouncePath,html);}}

const convertflowTrackingUrl='https://app.convertflow.com/refer?fpr=sangkwon-an-334dcb';
for(const file of ['public/tool/convertflow.html','public/best/convertflow-free-plan-pricing.html','public/compare/convertflow-vs-unbounce.html']){
  if(!fs.existsSync(file))continue;
  let html=fs.readFileSync(file,'utf8');
  html=html.replaceAll('data-cta="official" data-tool-id="convertflow"','data-cta="affiliate" data-tool-id="convertflow"');
  html=html.replace(/(<a data-cta="affiliate" data-tool-id="convertflow"[^>]*?)href="https:\/\/www\.convertflow\.com\/(?:pricing)?"/g, '$1href="'+convertflowTrackingUrl+'"');
  html=html.replace(/<a data-cta="affiliate" data-tool-id="convertflow"[^>]*>/g, tag=>tag.replace('rel="noopener noreferrer"','rel="sponsored noopener noreferrer"'));
  html=html.replaceAll('COSHUMA has not verified an account-issued ConvertFlow customer referral URL. These are official non-affiliate links.','Eligible purchases through the ConvertFlow offer link may earn COSHUMA a commission at no additional cost to the buyer.');
  html=html.replaceAll('Official non-affiliate link. COSHUMA has not verified an account-issued ConvertFlow customer referral URL.','Affiliate disclosure: COSHUMA may earn a commission if you purchase through this link, at no extra cost to you.');
  html=html.replaceAll('Not yet. COSHUMA has contacted ConvertFlow for the current enrollment path but has not verified an account-issued customer referral URL, so current buttons are official non-affiliate links.','Yes. This page links to the current ConvertFlow offer. Confirm current pricing and eligibility at the destination.');
  html=html.replaceAll('No. COSHUMA has not verified an account-issued ConvertFlow customer referral URL, so this page uses official non-affiliate links only.','Yes. This page links to the current ConvertFlow offer. Confirm current pricing and eligibility at the destination.');
  html=html.replaceAll('ConvertFlow\'s pricing page advertises free no-card entry. COSHUMA created one account, but that workspace is currently stuck on an Upgrade to ConvertFlow Pro screen; this support case is not evidence that every buyer will encounter the same issue.','ConvertFlow\'s pricing page advertises free no-card entry, and ConvertFlow advertises a no-card free entry point. Confirm current plan limits before relying on it.');
  html=html.replaceAll('COSHUMA created one free account after ConvertFlow support confirmed the enrollment path, but Continue on free plan currently returns to the Pro upgrade screen. Support has been asked once to restore free access. Do not interpret this as a verified paid-plan requirement, and do not pay solely to reach the referral dashboard.','COSHUMA’s authenticated account reached the free dashboard and completed referral enrollment on September 15, 2026. A paid upgrade was not required to obtain the account-issued referral link.');
  html=html.replaceAll('ConvertFlow\'s current knowledge base documents a referral partner program with an account-issued link and 30% commission on eligible self-service subscriptions for up to 12 months. ConvertFlow support confirmed the free-account-first path, and COSHUMA created one support@coshuma.com account. That account is currently blocked at the Pro upgrade gate, so support access help is pending and no affiliate dashboard or customer referral URL has been reached. No approval, customer referral URL, signup, paid customer, commission or revenue is assumed.','ConvertFlow offers a free entry point and paid plans based on plan scope and funnel traffic. Confirm current pricing and limits at the destination.');
  html=html.replaceAll('ConvertFlow advertises no-card free entry. COSHUMA created one account after support confirmed that path, but the workspace currently loops back to an Upgrade to ConvertFlow Pro screen when Continue on free plan is selected. Support has been contacted once, so verify that free access works in your own account before planning around it.','ConvertFlow advertises no-card free entry, and ConvertFlow advertises a no-card free entry point. Confirm current plan limits before relying on it. Buyers should still recheck current plan limits before purchase.');
  html=html.replaceAll('COSHUMA\'s account-access issue is being handled in the existing support thread. No paid upgrade, second account or duplicate request is warranted while free access is unresolved, and no customer referral URL is currently verified.','ConvertFlow advertises a no-card free entry point; confirm current plan limits and billing terms before purchase.');
  fs.writeFileSync(file,html);
}
console.log('ConvertFlow approved tracking, revenue truth and verified CTA state ensured');
