import fs from 'node:fs';

const checkedAt='2026-09-14T09:38:00+09:00';
const justuno={
  id:'justuno',name:'Justuno',category:'dev_coding',category_display:'Coding & Dev Tools',
  description:'Onsite conversion and visitor-identification platform for popups, workflows, targeting, personalization and ecommerce product recommendations.',
  affiliate_url:null,
  pricing:'Current Lite display: $59/month in annual-save context, up to 10,000 visitors/month, all features, 5 live workflows, 14-day free trial; paid pricing varies with traffic and billing selectors',
  key_features:['Website popups and onsite workflows','Visitor identification','Audience targeting and personalization','A/B and multivariate testing','AI product recommendations'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=justuno.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://www.justuno.com/',pricing_source_url:'https://www.justuno.com/pricing',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on plan and traffic',
  evidence_source_type:'official_pricing_and_affiliate_pages',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://www.justuno.com/affiliate',
  affiliate_verified:false,affiliate_status:'browser_required_partnerstack_application',affiliate_source_url:'https://www.justuno.com/affiliate',affiliate_workflow_url:'https://www.justuno.com/affiliate',affiliate_status_checked_at:checkedAt,application_state:'not_submitted',
  affiliate_evidence_markers:[
    'Official Justuno affiliate page says applicants use PartnerStack, receive a unique referral link, and earn 30% of eligible new-customer plan cost for up to one year.',
    'Official affiliate page says PartnerStack can track clicks, trials, referrals and payouts; this program capability is not evidence of COSHUMA account activity.',
    'Official pricing page currently displays Lite at $59/month in an annual-save context, up to 10K visitors/month, all features, 5 live workflows and a 14-day free trial.',
    'Fresh GitHub code search on 2026-09-14 found no pre-existing Justuno tool/state/page record before this cycle.',
    'Fresh support@coshuma.com Gmail searches found no Justuno received, sent or spam record.',
    'No COSHUMA application submission, approval, rejection, account-specific referral URL, trial, paid customer, commission, payout or revenue is verified.',
    'Generic homepage, signup, login, onboarding and PartnerStack dashboard URLs must not be treated as affiliate links.',
    'GitHub issue #493 tracks PartnerStack duplicate-check/application and exact account-issued customer referral URL recovery.'
  ],
  affiliate_next_action:'Reuse the existing COSHUMA PartnerStack identity, check for an existing Justuno relationship first, and submit exactly once only if absent. Stop for CAPTCHA, OTP, legal/program consent, forced identity verification or payment approval. After approval, recover and validate only the exact vendor-issued customer-facing referral URL.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===justuno.id);if(existing)Object.assign(existing,justuno);else tools.push(justuno);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}

const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.justuno={status:'browser_required_partnerstack_application',tracking_url:null,application_state:'not_submitted',account:'support@coshuma.com',official_program_url:'https://www.justuno.com/affiliate',workflow_url:'https://www.justuno.com/affiliate',github_issue:493,checked_at:checkedAt,note:'Official PartnerStack affiliate program advertises 30% of eligible new-customer plan cost for up to one year. No COSHUMA Justuno application submission, approval or account-specific referral URL is proven; public CTAs remain official non-affiliate URLs.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);

const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));let item=queue.find(i=>i.tool_id==='justuno'||String(i.id||'').startsWith('justuno-affiliate-'));const patch={tool_id:'justuno',priority:'high',status:'browser_required_partnerstack_application',affiliate_status:'browser_required_partnerstack_application',application_state:'not_submitted',cost:0,exact_tracking_url:null,user_action_required:false,blocker:'Justuno uses an authenticated PartnerStack application flow; the current direct connector set cannot inspect or submit that authenticated relationship safely.',reason:'Fresh repository and Gmail duplicate checks are clear and the official affiliate application path is known, but no submission or issued customer referral URL is verified.',official_program_url:'https://www.justuno.com/affiliate',next_action:'Reuse the existing COSHUMA PartnerStack account, check for an existing Justuno relationship first, and submit once only if absent. Stop for CAPTCHA, OTP, legal/program consent, forced identity verification or payment approval. Recover only the exact vendor-issued customer referral URL after approval.',do_not_reapply:true,verified_at:checkedAt,github_issue:493};if(item)Object.assign(item,patch);else queue.push({id:'justuno-affiliate-application-20260914',...patch});fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);

const urls=['https://coshuma.com/tool/justuno.html','https://coshuma.com/best/justuno-free-trial-pricing.html','https://coshuma.com/compare/justuno-vs-optimonk.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);

const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/justuno.html'))llms+='\n## Justuno buyer guides\n\n- https://coshuma.com/tool/justuno.html — Justuno trial, CRO workflow and product-fit buyer guide\n- https://coshuma.com/best/justuno-free-trial-pricing.html — Justuno free-trial and upgrade decision guide\n- https://coshuma.com/compare/justuno-vs-optimonk.html — Justuno vs OptiMonk CRO comparison\n';fs.writeFileSync(llmsPath,llms);

const hubBlock=`\n<section data-justuno-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-sky-500/25 bg-sky-500/5 p-5"><div class="text-xs uppercase tracking-widest text-sky-300 font-bold">Conversion optimization</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-sky-300" href="/best/justuno-free-trial-pricing.html">Justuno trial & pricing</a> · <a class="font-bold text-white hover:text-sky-300" href="/tool/justuno.html">Justuno buyer guide</a> · <a class="font-bold text-white hover:text-sky-300" href="/compare/justuno-vs-optimonk.html">Justuno vs OptiMonk</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-justuno-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}

const optimonkPath='public/tool/optimonk.html';if(fs.existsSync(optimonkPath)){let html=fs.readFileSync(optimonkPath,'utf8');if(!html.includes('data-justuno-related="2026-09-14"')){const links=`<section data-justuno-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-sky-500/25 bg-sky-500/5 p-6"><h2 class="text-xl font-black text-white">Want a time-limited CRO trial instead?</h2><p class="mt-2 text-sm text-slate-300">Justuno currently offers a 14-day Lite trial, while OptiMonk uses a permanent traffic-capped Free plan.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/justuno-vs-optimonk.html" class="rounded-xl bg-sky-600 px-5 py-3 text-center text-sm font-black text-white">Justuno vs OptiMonk →</a><a href="/tool/justuno.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">Justuno buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(optimonkPath,html);}}
console.log('Justuno fast-lane state, discoverability and PartnerStack application state ensured');
