import fs from 'node:fs';
import './ensure_justuno_fastlane.mjs';

const checkedAt='2026-09-14T09:33:00+09:00';
const optimonk={
  id:'optimonk',name:'OptiMonk',category:'dev_coding',category_display:'Coding & Dev Tools',
  description:'Conversion-rate optimization platform for popups, embedded campaigns, targeting, personalization and experimentation.',
  affiliate_url:null,
  pricing:'Free plan at $0 for up to 10,000 pageviews/month on one domain with unlimited campaigns and all features; paid tiers scale by traffic and billing period',
  key_features:['Popup and embedded campaigns','Behavioral targeting','Personalization','A/B and conversion experimentation','Ecommerce conversion optimization'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=optimonk.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://www.optimonk.com/',pricing_source_url:'https://www.optimonk.com/pricing',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on plan and traffic',
  evidence_source_type:'official_pricing_partner_and_help_pages',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://www.optimonk.com/partners-program',
  affiliate_verified:false,affiliate_status:'browser_required_affiliate_application',affiliate_source_url:'https://www.optimonk.com/partners-program',affiliate_workflow_url:'https://www.optimonk.com/partners-program',affiliate_status_checked_at:checkedAt,application_state:'not_submitted',
  affiliate_evidence_markers:[
    'Official OptiMonk pricing page shows a permanent $0 Free plan with 10,000 pageviews/month, max 1 domain, unlimited campaigns and all features.',
    'Official OptiMonk partner page says the Affiliate option has no membership fees, everyone can apply, and advertises 20% revenue share for 2 years.',
    'Some official OptiMonk help-center pages use broader lifetime/up-to-20% wording, so COSHUMA uses the more conservative current partner-page terms until the vendor clarifies.',
    'Fresh GitHub code search on 2026-09-14 found no pre-existing OptiMonk tool/state/page record before this cycle.',
    'Fresh support@coshuma.com Gmail searches found no OptiMonk received, sent or spam record.',
    'No COSHUMA application submission, approval, rejection, account-specific referral URL, referral, paid customer, commission, payout or revenue is verified.',
    'Generic homepage, signup, login, onboarding and dashboard URLs must not be treated as affiliate links.',
    'GitHub issue #491 tracks the free application and exact account-issued customer referral URL recovery.'
  ],
  affiliate_next_action:'Use the official OptiMonk affiliate route with the COSHUMA company identity, recheck for an existing account/application in the authenticated flow, and submit exactly once only if absent. Stop for CAPTCHA, OTP, legal/program consent, forced identity verification or payment approval. After approval, recover and validate only the exact vendor-issued customer-facing referral URL.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===optimonk.id);if(existing)Object.assign(existing,optimonk);else tools.push(optimonk);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}

const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.optimonk={status:'browser_required_affiliate_application',tracking_url:null,application_state:'not_submitted',account:'support@coshuma.com',official_program_url:'https://www.optimonk.com/partners-program',workflow_url:'https://www.optimonk.com/partners-program',github_issue:491,checked_at:checkedAt,note:'Official affiliate option is free to apply and current partner-page wording advertises 20% revenue share for 2 years. No COSHUMA application submission, approval or account-specific customer referral URL is proven; public CTAs remain official non-affiliate URLs.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);

const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));let item=queue.find(i=>i.tool_id==='optimonk'||String(i.id||'').startsWith('optimonk-affiliate-'));const patch={tool_id:'optimonk',priority:'high',status:'browser_required_affiliate_application',affiliate_status:'browser_required_affiliate_application',application_state:'not_submitted',cost:0,exact_tracking_url:null,user_action_required:false,blocker:'OptiMonk affiliate application and any account-issued referral URL require an authenticated vendor flow that is not available in the current direct connector set.',reason:'Fresh repository and Gmail duplicate checks are clear and the official affiliate option is free, but no application submission or issued customer referral URL is verified.',official_program_url:'https://www.optimonk.com/partners-program',next_action:'Use the official OptiMonk affiliate route with support@coshuma.com, check for an existing account/application first, and submit once only if absent. Stop for CAPTCHA, OTP, legal/program consent, forced identity verification or payment approval. Recover only the exact vendor-issued customer referral URL after approval.',do_not_reapply:true,verified_at:checkedAt,github_issue:491};if(item)Object.assign(item,patch);else queue.push({id:'optimonk-affiliate-application-20260914',...patch});fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);

const urls=['https://coshuma.com/tool/optimonk.html','https://coshuma.com/best/optimonk-free-plan-pricing.html','https://coshuma.com/compare/optimonk-vs-popupsmart.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);

const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/optimonk.html'))llms+='\n## OptiMonk buyer guides\n\n- https://coshuma.com/tool/optimonk.html — OptiMonk free plan, CRO workflow and product-fit buyer guide\n- https://coshuma.com/best/optimonk-free-plan-pricing.html — OptiMonk free-plan and upgrade decision guide\n- https://coshuma.com/compare/optimonk-vs-popupsmart.html — OptiMonk vs Popupsmart onsite-conversion comparison\n';fs.writeFileSync(llmsPath,llms);

const hubBlock=`\n<section data-optimonk-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-5"><div class="text-xs uppercase tracking-widest text-emerald-300 font-bold">Conversion optimization</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-emerald-300" href="/best/optimonk-free-plan-pricing.html">OptiMonk free plan & pricing</a> · <a class="font-bold text-white hover:text-emerald-300" href="/tool/optimonk.html">OptiMonk buyer guide</a> · <a class="font-bold text-white hover:text-emerald-300" href="/compare/optimonk-vs-popupsmart.html">OptiMonk vs Popupsmart</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-optimonk-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}

const popupsmartPath='public/tool/popupsmart.html';if(fs.existsSync(popupsmartPath)){let html=fs.readFileSync(popupsmartPath,'utf8');if(!html.includes('data-optimonk-related="2026-09-14"')){const links=`<section data-optimonk-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-emerald-500/25 bg-emerald-500/5 p-6"><h2 class="text-xl font-black text-white">Compare another free-entry CRO option</h2><p class="mt-2 text-sm text-slate-300">OptiMonk currently offers a larger free pageview allowance and positions itself as a broader CRO and personalization platform.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/optimonk-vs-popupsmart.html" class="rounded-xl bg-emerald-600 px-5 py-3 text-center text-sm font-black text-white">OptiMonk vs Popupsmart →</a><a href="/tool/optimonk.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">OptiMonk buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(popupsmartPath,html);}}
console.log('OptiMonk fast-lane state, discoverability and browser-required application state ensured');
