import fs from './affiliate_state_fs.mjs';

const checkedAt='2026-09-14T08:31:00+09:00';
const affiliateCheckedAt='2026-10-07T21:24:00+09:00';
const creatify={
  id:'creatify',name:'Creatify',category:'video_gen',category_display:'Video & Shorts Gen',
  description:'AI advertising creative platform for turning product links and briefs into video and image ads with AI actors, templates and ad-focused creation workflows.',
  affiliate_url:null,
  pricing:'Free plan with 10 monthly credits; paid Starter, Pro and Enterprise/Custom plans are available',
  key_features:['AI video ads','AI image ads','AI actors','Ad templates and creative workflows','Product-link driven ad creation'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=creatify.ai&sz=128',primary_category:'video_gen',comparison_group:'ai_ad_creative',
  official_url:'https://creatify.ai/',pricing_source_url:'https://creatify.ai/pricing',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on plan',
  evidence_source_type:'official_pricing_help_and_affiliate_pages',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://creatify.ai/affiliate',
  affiliate_verified:false,affiliate_status:'application_available_account_required',affiliate_source_url:'https://creatify.ai/affiliate',affiliate_workflow_url:'https://docs.google.com/forms/d/e/1FAIpQLSc_k126zcElDxMgsaqO7WJOTMLUS0JPhqiNOAgzrGmJMC2ZAA/viewform',affiliate_status_checked_at:affiliateCheckedAt,application_state:'not_submitted',
  affiliate_evidence_markers:[
    'Official Creatify affiliate page says the program is free to join and advertises 25% recurring commission on qualifying purchases.',
    'Official program says applicants receive a unique link and affiliate dashboard after signup; that public statement is not evidence that COSHUMA is approved.',
    'The current official Google application form was read directly on 2026-10-07 and requires a Creatify account plus applicant, channel, audience and monthly reach details; no existing COSHUMA Creatify account is evidenced.',
    'Official pricing/help confirms a free plan with 10 monthly credits, with current pricing FAQ describing up to 2 video ads or 20 image ads and watermarked exports.',
    'Fresh support@coshuma.com Gmail in:anywhere search on 2026-09-14 found no Creatify received, sent, spam, trash, application, approval, rejection, tracking-link, commission or payout record.',
    'Repository already contained a 2026-09-12 Creatify affiliate candidate queue item but no verified account-specific tracking URL or Creatify product page before this fast-lane cycle.',
    'Exact COSHUMA customer referral URL remains unknown; affiliate/dashboard/login/onboarding/homepage URLs must not be used as affiliate CTAs.',
    'GitHub issue #487 tracks the free application and exact vendor-issued referral URL recovery.'
  ],
  affiliate_next_action:'Confirm an existing COSHUMA-owned Creatify account before applying. If none is evidenced, keep the application on hold; do not create a new vendor account. If an existing account is confirmed, submit the official Google form once with verified COSHUMA details and actual reach only. After approval, recover and validate only the vendor-issued customer-facing referral URL.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===creatify.id);if(existing)Object.assign(existing,creatify);else tools.push(creatify);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}
const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.creatify={status:'application_available_account_required',tracking_url:null,application_state:'not_submitted',account:'support@coshuma.com',official_program_url:'https://creatify.ai/affiliate',workflow_url:'https://docs.google.com/forms/d/e/1FAIpQLSc_k126zcElDxMgsaqO7WJOTMLUS0JPhqiNOAgzrGmJMC2ZAA/viewform',github_issue:487,checked_at:affiliateCheckedAt,note:'Official program is free and advertises 25% recurring commission. The current official application form requires a Creatify account and verified applicant/channel/reach details. No existing COSHUMA Creatify account, application, approval or account-specific referral URL is proven; customer CTAs remain official non-affiliate URLs.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);
const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));let item=queue.find(i=>i.tool_id==='creatify'||String(i.id||'').startsWith('creatify-affiliate-'));const patch={tool_id:'creatify',priority:'high',status:'application_available_account_required',affiliate_status:'application_available_account_required',application_state:'not_submitted',cost:0,exact_tracking_url:null,user_action_required:false,blocker:'The official Creatify Google application form requires a Creatify account plus verified applicant, promotion-channel, audience and monthly-reach details; no existing COSHUMA Creatify account is evidenced.',reason:'The official program remains free and advertises 25% recurring commission, but no existing COSHUMA Creatify account, application submission or issued account-specific link is verified.',official_program_url:'https://creatify.ai/affiliate',next_action:'Confirm an existing COSHUMA-owned Creatify account before applying. If none is evidenced, keep on hold and do not create a new vendor account. If an existing account is confirmed, submit once with verified COSHUMA details and actual reach only, then recover only the exact vendor-issued referral URL after approval.',do_not_reapply:true,verified_at:affiliateCheckedAt,github_issue:487};if(item)Object.assign(item,patch);else queue.push({id:'creatify-affiliate-application-20260914',...patch});fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);
const urls=['https://coshuma.com/tool/creatify.html','https://coshuma.com/best/creatify-free-plan-pricing.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);
const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/creatify.html'))llms+='\n## Creatify buyer guides\n\n- https://coshuma.com/tool/creatify.html — Creatify AI ad-creative product and product-fit buyer guide\n- https://coshuma.com/best/creatify-free-plan-pricing.html — Creatify free-plan and upgrade decision guide\n- https://coshuma.com/compare/tagshop-ai-vs-creatify.html — Tagshop AI vs Creatify AI UGC-ad comparison\n';fs.writeFileSync(llmsPath,llms);
const hubBlock=`\n<section data-creatify-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-purple-500/25 bg-purple-500/5 p-5"><div class="text-xs uppercase tracking-widest text-purple-300 font-bold">AI ad creative</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-purple-300" href="/best/creatify-free-plan-pricing.html">Creatify free plan & pricing</a> · <a class="font-bold text-white hover:text-purple-300" href="/tool/creatify.html">Creatify buyer guide</a> · <a class="font-bold text-white hover:text-purple-300" href="/compare/tagshop-ai-vs-creatify.html">Tagshop AI vs Creatify</a></p></div></section>\n`;for(const file of ['public/best/index.html','index.html']){let html=fs.readFileSync(file,'utf8');if(!html.includes('data-creatify-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}
const comparePath='public/compare/tagshop-ai-vs-creatify.html';if(fs.existsSync(comparePath)){let html=fs.readFileSync(comparePath,'utf8');if(!html.includes('data-creatify-buyer-links="2026-09-14"')){const links=`<section data-creatify-buyer-links="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-violet-500/25 bg-violet-500/5 p-6"><h2 class="text-xl font-black text-white">Need the Creatify details first?</h2><p class="mt-2 text-sm text-slate-300">Check Creatify's current free-plan limits and independent product guide before choosing between ad-creative workflows.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/tool/creatify.html" class="rounded-xl bg-violet-600 px-5 py-3 text-center text-sm font-black text-white">Creatify buyer guide →</a><a href="/best/creatify-free-plan-pricing.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">Creatify free-plan guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(comparePath,html);}}
console.log('Creatify fast-lane state, discoverability and account-required application state ensured');
