import fs from 'node:fs';

const checkedAt='2026-09-14T12:34:00+09:00';
const claspo={
  id:'claspo',name:'Claspo',category:'dev_coding',category_display:'Conversion Optimization',
  description:'Popup and onsite-widget platform for lead capture, forms, announcements and conversion campaigns.',
  affiliate_url:null,
  pricing:'$0/month permanent Free plan; current Free selection shows 3,000 pageviews/month, 1 website, all features, unlimited widgets and team members, with a Powered by Claspo badge',
  key_features:['Popups and onsite widgets','Lead capture forms','Targeting and triggers','Unlimited widgets on Free','A/B testing and conversion tools'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=claspo.io&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://claspo.io/',pricing_source_url:'https://claspo.io/pricing/',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'permanent free tier or paid plan',
  evidence_source_type:'official_pricing_affiliate_and_terms_pages',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://claspo.io/affiliate-program/',
  affiliate_verified:false,affiliate_status:'browser_required_legal_program_consent',affiliate_source_url:'https://claspo.io/affiliate-program/',affiliate_workflow_url:'https://claspo.firstpromoter.com/',affiliate_status_checked_at:checkedAt,application_state:'not_submitted_legal_consent_required',
  affiliate_evidence_markers:[
    'Official Claspo pricing advertises a permanent $0/month Free plan with no time limit; the current selector shows 3,000 pageviews/month, one website, all features, unlimited widgets and team members, and a Powered by Claspo badge.',
    'Claspo separately offers a 14-day paid-plan trial that currently requires billing details and can auto-charge after the trial; COSHUMA does not start that paid path.',
    'Official affiliate page says applicants receive a unique referral link and referral tracking remains active for 120 days.',
    'Current affiliate terms say application submission constitutes acceptance of the affiliate agreement and business/site representations, so unattended legal consent is not permitted.',
    'Current affiliate terms say only paid subscriptions count as sales, use last-click attribution, and payout eligibility requires five or more paying customers via the referral link.',
    'The public affiliate documents checked this cycle do not expose a reliable fixed affiliate commission percentage; COSHUMA leaves the rate unknown rather than infer it from the separate agency program.',
    'Fresh GitHub and support@coshuma.com Gmail checks found no prior Claspo application, approval, rejection, tracking-link, commission or payout record before this cycle.',
    'Exact account-issued customer referral URL is unknown; clicks, signups, paid customers, commission, payout and revenue remain unknown.',
    'GitHub issue #503 tracks legal-consent-gated application and exact referral-link recovery.'
  ],
  affiliate_next_action:'The account holder must review and accept the Claspo Affiliate Program terms in the official FirstPromoter application before submission. Submit once only if accepted, then recover and verify only the exact customer-facing referral URL actually issued. Stop for CAPTCHA, OTP, payment approval, forced identity verification or any additional legal consent.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===claspo.id);if(existing)Object.assign(existing,claspo);else tools.push(claspo);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}
const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.claspo={status:'browser_required_legal_program_consent',tracking_url:null,application_state:'not_submitted_legal_consent_required',account:'support@coshuma.com',official_program_url:'https://claspo.io/affiliate-program/',workflow_url:'https://claspo.firstpromoter.com/',github_issue:503,checked_at:checkedAt,note:'Direct FirstPromoter program found with a unique referral link and 120-day tracking, but the application itself is legal program consent. No application was submitted unattended. Exact tracking URL and all revenue stages remain unknown.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);
const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));if(!queue.some(i=>i.tool_id==='claspo'||String(i.id||'').startsWith('claspo-'))){queue.push({id:'claspo-affiliate-2026-09-14',tool_id:'claspo',priority:'high',status:'browser_required_legal_program_consent',affiliate_status:'browser_required_legal_program_consent',application_state:'not_submitted_legal_consent_required',cost:0,exact_tracking_url:null,user_action_required:true,blocker:'Submitting the official FirstPromoter application constitutes acceptance of Claspo affiliate legal terms and applicant/business/site representations.',reason:'Repository and Gmail duplicate checks are clear and the program is free, but legal/program consent belongs to the account holder.',next_action:'Open the official Claspo FirstPromoter application, review and accept the linked Affiliate Program terms only if the account holder agrees, submit once, then recover only the exact vendor-issued customer referral URL. Stop for CAPTCHA, OTP, additional legal consent, forced identity verification or payment approval.',do_not_reapply:true,verified_at:checkedAt,github_issue:503});}fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);
const urls=['https://coshuma.com/tool/claspo.html','https://coshuma.com/best/claspo-free-plan-pricing.html','https://coshuma.com/compare/claspo-vs-poptin.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);
const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/claspo.html'))llms+='\n## Claspo buyer guides\n\n- https://coshuma.com/tool/claspo.html — Claspo free plan, popup/widget features, paid-trial caution and affiliate-status buyer guide\n- https://coshuma.com/best/claspo-free-plan-pricing.html — Claspo permanent free plan and billing-risk decision guide\n- https://coshuma.com/compare/claspo-vs-poptin.html — Claspo vs Poptin free popup-tool comparison\n';fs.writeFileSync(llmsPath,llms);
const hubBlock=`\n<section data-claspo-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-sky-500/25 bg-sky-500/5 p-5"><div class="text-xs uppercase tracking-widest text-sky-300 font-bold">Popups & onsite conversion</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-sky-300" href="/best/claspo-free-plan-pricing.html">Claspo free plan & pricing</a> · <a class="font-bold text-white hover:text-sky-300" href="/tool/claspo.html">Claspo buyer guide</a> · <a class="font-bold text-white hover:text-sky-300" href="/compare/claspo-vs-poptin.html">Claspo vs Poptin</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-claspo-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}
const poptinPath='public/tool/poptin.html';if(fs.existsSync(poptinPath)){let html=fs.readFileSync(poptinPath,'utf8');if(!html.includes('data-claspo-related="2026-09-14"')){const links=`<section data-claspo-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-sky-500/25 bg-sky-500/5 p-6"><h2 class="text-xl font-black text-white">Compare another permanent-free popup tool</h2><p class="mt-2 text-sm text-slate-300">Claspo and Poptin both offer permanent free entry, but Claspo publishes pageviews while Poptin publishes visitors. Treat those limits as different measurements.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/claspo-vs-poptin.html" class="rounded-xl bg-sky-600 px-5 py-3 text-center text-sm font-black text-white">Claspo vs Poptin →</a><a href="/tool/claspo.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">Claspo buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(poptinPath,html);}}
console.log('Claspo fast-lane state, legal-consent browser queue and discoverability ensured');
