import fs from 'node:fs';

const checkedAt='2026-09-14T10:25:00+09:00';
const sleeknote={
  id:'sleeknote',name:'Sleeknote',category:'dev_coding',category_display:'Coding & Dev Tools',
  description:'Onsite conversion platform for lead capture, product promotion, visitor guidance, gamification and customer-contact campaigns.',
  affiliate_url:null,
  pricing:'14-day free trial with all products/features and no credit card required; current Core display for 0–25K monthly visitors is $69/month monthly billing or $55/month annual billing; pricing varies by visitor tier and billing frequency',
  key_features:['Lead-capture popups and forms','Product-promotion campaigns','Visitor guidance and onsite messaging','Gamification','Audience segmentation and targeting'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=sleeknote.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://sleeknote.com/',pricing_source_url:'https://sleeknote.com/pricing',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on visitor tier and billing choice',
  evidence_source_type:'official_pricing_partner_pages_and_gmail_sent',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://sleeknote.com/partner-program',
  affiliate_verified:false,affiliate_status:'waiting_vendor_response',affiliate_source_url:'https://sleeknote.com/partner-program',affiliate_workflow_url:'https://sleeknote.com/partner-program',affiliate_status_checked_at:checkedAt,application_state:'contact_sent_waiting_application_path',
  affiliate_evidence_markers:[
    'Official Sleeknote partner page says the program is free to apply for and currently shows tiered monthly recurring commission: 10% for 1-9 referrals, 15% for 10-24, and 25% for 25+.',
    'Official partner page says applicants fill in a form and commission starts after at least one referred client and signing the contract.',
    'Official pricing page currently advertises a 14-day free trial with all products/features and no credit card required.',
    'For 0-25K monthly visitors, the current Core display is $69/month monthly billing or $55/month annual billing; purchase-day pricing must be rechecked.',
    'Fresh GitHub code/open-issue and support@coshuma.com received/sent/spam checks found no pre-existing Sleeknote application or relationship before this cycle.',
    'On 2026-09-14 COSHUMA sent one first-contact partner-program email to Sleeknote official contact mail@sleeknote.com requesting the correct application path under support@coshuma.com.',
    'No COSHUMA approval, account-issued customer referral URL, click, referred signup, paid customer, commission, payout or revenue is verified.',
    'Generic homepage, signup, onboarding and Rewardful partner-login/dashboard URLs must not be treated as affiliate links.',
    'GitHub issue #495 tracks the vendor response, exact application path and future customer referral URL recovery.'
  ],
  affiliate_next_action:'Wait for the existing Sleeknote email thread response and do not resend or duplicate-apply. If the vendor supplies a specific application/account flow, use it once and stop for CAPTCHA, OTP, legal/program contract consent, forced identity verification or payment approval. After approval, recover and validate only the exact account-issued customer-facing referral URL.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===sleeknote.id);if(existing)Object.assign(existing,sleeknote);else tools.push(sleeknote);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}

const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.sleeknote={status:'waiting_vendor_response',tracking_url:null,application_state:'contact_sent_waiting_application_path',account:'support@coshuma.com',official_program_url:'https://sleeknote.com/partner-program',workflow_url:'https://sleeknote.com/partner-program',contact_email:'mail@sleeknote.com',github_issue:495,checked_at:checkedAt,note:'Fresh duplicate checks were clear. One first-contact partner-program email was sent on 2026-09-14 asking for the correct application path under support@coshuma.com. No approval or account-issued customer referral URL is proven; public Sleeknote CTAs remain official non-affiliate URLs. Do not resend while waiting.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);

const urls=['https://coshuma.com/tool/sleeknote.html','https://coshuma.com/best/sleeknote-free-trial-pricing.html','https://coshuma.com/compare/sleeknote-vs-justuno.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);

const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/sleeknote.html'))llms+='\n## Sleeknote buyer guides\n\n- https://coshuma.com/tool/sleeknote.html — Sleeknote trial, pricing, onsite-conversion and partner-status buyer guide\n- https://coshuma.com/best/sleeknote-free-trial-pricing.html — Sleeknote free-trial and upgrade decision guide\n- https://coshuma.com/compare/sleeknote-vs-justuno.html — Sleeknote vs Justuno onsite-conversion comparison\n';fs.writeFileSync(llmsPath,llms);

const hubBlock=`\n<section data-sleeknote-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-fuchsia-500/25 bg-fuchsia-500/5 p-5"><div class="text-xs uppercase tracking-widest text-fuchsia-300 font-bold">Onsite conversion</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-fuchsia-300" href="/best/sleeknote-free-trial-pricing.html">Sleeknote trial & pricing</a> · <a class="font-bold text-white hover:text-fuchsia-300" href="/tool/sleeknote.html">Sleeknote buyer guide</a> · <a class="font-bold text-white hover:text-fuchsia-300" href="/compare/sleeknote-vs-justuno.html">Sleeknote vs Justuno</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-sleeknote-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}

const justunoPath='public/tool/justuno.html';if(fs.existsSync(justunoPath)){let html=fs.readFileSync(justunoPath,'utf8');if(!html.includes('data-sleeknote-related="2026-09-14"')){const links=`<section data-sleeknote-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-fuchsia-500/25 bg-fuchsia-500/5 p-6"><h2 class="text-xl font-black text-white">Compare another 14-day onsite-conversion trial</h2><p class="mt-2 text-sm text-slate-300">Sleeknote currently advertises a 14-day no-card trial with an entry Core tier covering up to 25,000 monthly visitors; Justuno's current Lite display uses a 10,000-visitor allowance.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/sleeknote-vs-justuno.html" class="rounded-xl bg-fuchsia-600 px-5 py-3 text-center text-sm font-black text-white">Sleeknote vs Justuno →</a><a href="/tool/sleeknote.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">Sleeknote buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(justunoPath,html);}}
console.log('Sleeknote fast-lane state, discoverability and vendor-waiting state ensured');
