import fs from 'node:fs';

const checkedAt='2026-09-14T10:33:00+09:00';
const convertflow={
  id:'convertflow',name:'ConvertFlow',category:'dev_coding',category_display:'Coding & Dev Tools',
  description:'Funnel builder for landing pages, lead forms, quizzes, popups, targeted offers, personalization and conversion experiments.',
  affiliate_url:null,
  pricing:'Free signup with no credit card required; current Personal display starts at $29/month monthly or $25/month annual-billing equivalent with up to 10K monthly funnel views; pricing varies by plan and traffic',
  key_features:['Landing-page funnels','Quiz and lead-form funnels','Popup funnels','Targeted offers and personalization','Conversion analytics and experiments'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=convertflow.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://www.convertflow.com/',pricing_source_url:'https://www.convertflow.com/pricing',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on plan and funnel traffic',
  evidence_source_type:'official_pricing_help_center_and_gmail_sent',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',
  affiliate_verified:false,affiliate_status:'waiting_vendor_response',affiliate_source_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',affiliate_workflow_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',affiliate_status_checked_at:checkedAt,application_state:'contact_sent_waiting_enrollment_path',
  affiliate_evidence_markers:[
    'Official ConvertFlow referral-program knowledge base says partners join from a ConvertFlow account, enter a PayPal payout email and receive a unique referral link in the affiliate dashboard.',
    'Current referral documentation states 30% commission on eligible self-service subscription renewals for up to 12 months and that self-referrals are not commissionable.',
    'Official pricing page currently says users can start free without a credit card; current Personal display starts at $29/month monthly or $25/month annual-billing equivalent with up to 10K monthly funnel views.',
    'Fresh GitHub code/open-issue and support@coshuma.com Gmail checks found no pre-existing ConvertFlow application or relationship before this cycle.',
    'On 2026-09-14 COSHUMA sent one first-contact enrollment-path email to official support@convertflow.com asking whether support@coshuma.com should create a free account first and then enroll from Partners.',
    'No COSHUMA approval, account-issued customer referral URL, click, signup, paid customer, commission, payout or revenue is verified.',
    'Generic homepage, signup, Partners navigation and affiliate dashboard URLs must not be treated as affiliate links.',
    'GitHub issue #497 tracks vendor response, exact enrollment path and future customer referral URL recovery.'
  ],
  affiliate_next_action:'Wait for the existing ConvertFlow support thread and do not resend or duplicate-enroll. If support confirms free-account-first enrollment, create or reuse exactly one support@coshuma.com account and proceed only until CAPTCHA, OTP, legal/program consent, forced identity verification or payment approval. After enrollment, recover and validate only the exact account-issued customer-facing referral URL.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===convertflow.id);if(existing)Object.assign(existing,convertflow);else tools.push(convertflow);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}
const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.convertflow={status:'waiting_vendor_response',tracking_url:null,application_state:'contact_sent_waiting_enrollment_path',account:'support@coshuma.com',official_program_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',workflow_url:'https://help.convertflow.com/article/154-how-to-join-the-convertflow-referral-program',contact_email:'support@convertflow.com',github_issue:497,checked_at:checkedAt,note:'Fresh duplicate checks were clear. One first-contact enrollment-path email was sent on 2026-09-14. No approval or account-issued customer referral URL is proven; public ConvertFlow CTAs remain official non-affiliate URLs. Do not resend while waiting.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);
const urls=['https://coshuma.com/tool/convertflow.html','https://coshuma.com/best/convertflow-free-plan-pricing.html','https://coshuma.com/compare/convertflow-vs-unbounce.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);
const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/convertflow.html'))llms+='\n## ConvertFlow buyer guides\n\n- https://coshuma.com/tool/convertflow.html — ConvertFlow free entry, funnel builder, pricing and referral-status buyer guide\n- https://coshuma.com/best/convertflow-free-plan-pricing.html — ConvertFlow free-plan and upgrade decision guide\n- https://coshuma.com/compare/convertflow-vs-unbounce.html — ConvertFlow vs Unbounce funnels and landing-page CRO comparison\n';fs.writeFileSync(llmsPath,llms);
const hubBlock=`\n<section data-convertflow-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-cyan-500/25 bg-cyan-500/5 p-5"><div class="text-xs uppercase tracking-widest text-cyan-300 font-bold">Funnels & CRO</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-cyan-300" href="/best/convertflow-free-plan-pricing.html">ConvertFlow free plan & pricing</a> · <a class="font-bold text-white hover:text-cyan-300" href="/tool/convertflow.html">ConvertFlow buyer guide</a> · <a class="font-bold text-white hover:text-cyan-300" href="/compare/convertflow-vs-unbounce.html">ConvertFlow vs Unbounce</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-convertflow-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}
const unbouncePath='public/tool/unbounce.html';if(fs.existsSync(unbouncePath)){let html=fs.readFileSync(unbouncePath,'utf8');if(!html.includes('data-convertflow-related="2026-09-14"')){const links=`<section data-convertflow-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-cyan-500/25 bg-cyan-500/5 p-6"><h2 class="text-xl font-black text-white">Compare a broader funnel builder</h2><p class="mt-2 text-sm text-slate-300">ConvertFlow currently offers a no-card free starting point for landing pages, forms, quizzes and popups. Compare it with Unbounce when deciding between broader funnel logic and dedicated landing-page CRO.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/convertflow-vs-unbounce.html" class="rounded-xl bg-cyan-600 px-5 py-3 text-center text-sm font-black text-white">ConvertFlow vs Unbounce →</a><a href="/tool/convertflow.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">ConvertFlow buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(unbouncePath,html);}}
console.log('ConvertFlow fast-lane state, discoverability and vendor-waiting state ensured');
