import fs from './affiliate_state_fs.mjs';

const checkedAt='2026-09-14T08:31:00+09:00';
const creatify={
  id:'creatify',name:'Creatify',category:'video_gen',category_display:'Video & Shorts Gen',
  description:'AI advertising creative platform for turning product links and briefs into video and image ads with AI actors, templates and ad-focused creation workflows.',
  affiliate_url:null,
  pricing:'Free plan with 10 monthly credits; paid Starter, Pro and Enterprise/Custom plans are available',
  key_features:['AI video ads','AI image ads','AI actors','Ad templates and creative workflows','Product-link driven ad creation'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=creatify.ai&sz=128',primary_category:'video_gen',comparison_group:'ai_ad_creative',
  official_url:'https://creatify.ai/',pricing_source_url:'https://creatify.ai/pricing',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'monthly or annual depending on plan',
  evidence_source_type:'official_pricing_help_and_affiliate_pages',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://creatify.ai/affiliate',
  affiliate_verified:false,affiliate_status:'browser_required_affiliate_application',affiliate_source_url:'https://creatify.ai/affiliate',affiliate_workflow_url:'https://creatify.ai/affiliate',affiliate_status_checked_at:checkedAt,application_state:'not_submitted',
  affiliate_evidence_markers:[
    'Official Creatify affiliate page says the program is free to join and advertises 25% recurring commission on qualifying purchases.',
    'Official program says applicants receive a unique link and affiliate dashboard after signup; that public statement is not evidence that COSHUMA is approved.',
    'Official pricing/help confirms a free plan with 10 monthly credits, with current pricing FAQ describing up to 2 video ads or 20 image ads and watermarked exports.',
    'Fresh support@coshuma.com Gmail in:anywhere search on 2026-09-14 found no Creatify received, sent, spam, trash, application, approval, rejection, tracking-link, commission or payout record.',
    'Repository already contained a 2026-09-12 Creatify affiliate candidate queue item but no verified account-specific tracking URL or Creatify product page before this fast-lane cycle.',
    'Exact COSHUMA customer referral URL remains unknown; affiliate/dashboard/login/onboarding/homepage URLs must not be used as affiliate CTAs.',
    'GitHub issue #487 tracks the free application and exact vendor-issued referral URL recovery.'
  ],
  affiliate_next_action:'Use the official Creatify affiliate route with the COSHUMA company identity, recheck for an existing account/application in the authenticated flow, and submit once only if absent. Stop for CAPTCHA, OTP, legal/program consent, forced identity verification or payment approval. After approval, recover and validate only the vendor-issued customer-facing referral URL.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===creatify.id);if(existing)Object.assign(existing,creatify);else tools.push(creatify);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}
const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.creatify={status:'browser_required_affiliate_application',tracking_url:null,application_state:'not_submitted',account:'support@coshuma.com',official_program_url:'https://creatify.ai/affiliate',workflow_url:'https://creatify.ai/affiliate',github_issue:487,checked_at:checkedAt,note:'Official program is free and advertises 25% recurring commission. Fresh Gmail duplicate check is clear. No COSHUMA application submission, approval or account-specific referral URL is proven; customer CTAs remain official non-affiliate URLs.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);
const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));let item=queue.find(i=>i.tool_id==='creatify'||String(i.id||'').startsWith('creatify-affiliate-'));const patch={tool_id:'creatify',priority:'high',status:'browser_required_affiliate_application',affiliate_status:'browser_required_affiliate_application',application_state:'not_submitted',cost:0,exact_tracking_url:null,user_action_required:false,blocker:'Creatify affiliate signup and any unique link require an authenticated vendor/Rewardful flow that is not available in the current direct connector set.',reason:'Fresh repository/Gmail duplicate checks are clear and the official program is free, but no application submission or issued account-specific link is verified.',official_program_url:'https://creatify.ai/affiliate',next_action:'Use the official Creatify affiliate route with support@coshuma.com, check for an existing account/application first, and submit once only if absent. Stop for CAPTCHA, OTP, legal/program consent, forced identity verification or payment approval. Recover only the exact vendor-issued referral URL after approval.',do_not_reapply:true,verified_at:checkedAt,github_issue:487};if(item)Object.assign(item,patch);else queue.push({id:'creatify-affiliate-application-20260914',...patch});fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);
const urls=['https://coshuma.com/tool/creatify.html','https://coshuma.com/best/creatify-free-plan-pricing.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);
const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/creatify.html'))llms+='\n## Creatify buyer guides\n\n- https://coshuma.com/tool/creatify.html — Creatify AI ad-creative product and product-fit buyer guide\n- https://coshuma.com/best/creatify-free-plan-pricing.html — Creatify free-plan and upgrade decision guide\n- https://coshuma.com/compare/tagshop-ai-vs-creatify.html — Tagshop AI vs Creatify AI UGC-ad comparison\n';fs.writeFileSync(llmsPath,llms);
const hubBlock=`\n<section data-creatify-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-purple-500/25 bg-purple-500/5 p-5"><div class="text-xs uppercase tracking-widest text-purple-300 font-bold">AI ad creative</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-purple-300" href="/best/creatify-free-plan-pricing.html">Creatify free plan & pricing</a> · <a class="font-bold text-white hover:text-purple-300" href="/tool/creatify.html">Creatify buyer guide</a> · <a class="font-bold text-white hover:text-purple-300" href="/compare/tagshop-ai-vs-creatify.html">Tagshop AI vs Creatify</a></p></div></section>\n`;for(const file of ['public/best/index.html','index.html']){let html=fs.readFileSync(file,'utf8');if(!html.includes('data-creatify-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}
const comparePath='public/compare/tagshop-ai-vs-creatify.html';if(fs.existsSync(comparePath)){let html=fs.readFileSync(comparePath,'utf8');if(!html.includes('data-creatify-buyer-links="2026-09-14"')){const links=`<section data-creatify-buyer-links="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-violet-500/25 bg-violet-500/5 p-6"><h2 class="text-xl font-black text-white">Need the Creatify details first?</h2><p class="mt-2 text-sm text-slate-300">Check Creatify's current free-plan limits and independent product guide before choosing between ad-creative workflows.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/tool/creatify.html" class="rounded-xl bg-violet-600 px-5 py-3 text-center text-sm font-black text-white">Creatify buyer guide →</a><a href="/best/creatify-free-plan-pricing.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">Creatify free-plan guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(comparePath,html);}}
console.log('Creatify fast-lane state, discoverability and browser-required application state ensured');
