import fs from './affiliate_state_fs.mjs';

const checkedAt='2026-09-14T11:26:00+09:00';
const adoric={
  id:'adoric',name:'Adoric',category:'dev_coding',category_display:'Coding & Dev Tools',
  description:'Onsite conversion platform for popups, forms, gamification, personalization, product recommendations and ecommerce conversion campaigns.',
  affiliate_url:null,
  pricing:'Non-Shopify Free plan up to 5,000 pageviews/month; Shopify popup product currently offers a 7-day free trial and order-volume-based paid pricing starting at $4.99/month for 0-100 monthly orders',
  key_features:['Popup and form campaigns','Audience targeting and personalization','A/B testing','Gamification and product recommendations','Shopify conversion and upsell tools'],
  rating:null,logo_url:'https://www.google.com/s2/favicons?domain=adoric.com&sz=128',primary_category:'dev_coding',comparison_group:'conversion_optimization',
  official_url:'https://adoric.com/',pricing_source_url:'https://help.adoric.com/en/article/pageviews-and-limitations-of-plans-wcm3c5/',pricing_verified_at:checkedAt,pricing_verified:true,currency:'USD',billing_period:'free tier for non-Shopify; Shopify pricing varies by monthly store orders',
  evidence_source_type:'official_help_center_and_affiliate_page',is_manual_override:true,official_verification_status:'verified',official_verified_at:checkedAt,official_evidence_url:'https://ftp.adoric.com/affiliate/',
  affiliate_verified:false,affiliate_status:'browser_required_account_registration',affiliate_source_url:'https://ftp.adoric.com/affiliate/',affiliate_workflow_url:'https://ftp.adoric.com/affiliate/',affiliate_status_checked_at:checkedAt,application_state:'not_submitted',
  affiliate_evidence_markers:[
    'Official Adoric affiliate page says the program is free to join and the affiliate area is available from a free Adoric account.',
    'Official affiliate page says the account affiliate area provides the referral link; generic signup, dashboard, homepage and affiliate-portal URLs are not customer tracking URLs.',
    'Current public affiliate terms advertise 20% of qualifying referred monthly payments for up to 12 months, a $100 payout threshold and PayPal payouts.',
    'Current Adoric help-center documentation for non-Shopify sites states a Free plan with up to 5,000 pageviews per month.',
    'Current Shopify-specific popup pricing documentation separately states a 7-day free trial and order-volume-based paid pricing, so COSHUMA keeps the two pricing models distinct.',
    'Fresh GitHub and support@coshuma.com Gmail checks found no pre-existing Adoric application, approval, rejection, tracking-link, commission or payout record before this cycle.',
    'Exact account-specific customer referral URL is unknown; no click, signup, paid customer, commission, payout or revenue is inferred.',
    'GitHub issue #499 tracks free account registration and exact vendor-issued referral URL recovery.'
  ],
  affiliate_next_action:'Use the official Adoric free-account route with support@coshuma.com, checking for an existing account first. If absent, register once at zero cost, then recover and validate only the exact customer-facing referral URL shown in the authenticated affiliate area. Stop for CAPTCHA, OTP, account-holder legal/program consent, forced identity verification or payment approval.'
};
for(const file of ['data/tools.json','data/tools.next.json']){const tools=JSON.parse(fs.readFileSync(file,'utf8'));const existing=tools.find(t=>t.id===adoric.id);if(existing)Object.assign(existing,adoric);else tools.push(adoric);fs.writeFileSync(file,`${JSON.stringify(tools,null,2)}\n`);}
const outreachPath='data/affiliate_outreach_state.json';const outreach=JSON.parse(fs.readFileSync(outreachPath,'utf8'));outreach.updated_at='2026-09-14';outreach.programs||={};outreach.programs.adoric={status:'browser_required_account_registration',tracking_url:null,application_state:'not_submitted',account:'support@coshuma.com',official_program_url:'https://ftp.adoric.com/affiliate/',workflow_url:'https://ftp.adoric.com/affiliate/',github_issue:499,checked_at:checkedAt,note:'Official Adoric affiliate program is free and issues the referral link from the authenticated account affiliate area. Fresh GitHub/Gmail duplicate checks are clear. No approval or customer tracking URL is proven; public Adoric CTAs remain official non-affiliate URLs.'};fs.writeFileSync(outreachPath,`${JSON.stringify(outreach,null,2)}\n`);
const queuePath='data/browser_required_queue.json';const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));if(!queue.some(i=>i.tool_id==='adoric'||String(i.id||'').startsWith('adoric-'))){queue.push({id:'adoric-affiliate-2026-09-14',tool_id:'adoric',priority:'high',status:'browser_required_account_registration',affiliate_status:'browser_required_account_registration',application_state:'not_submitted',cost:0,exact_tracking_url:null,user_action_required:false,blocker:'Adoric issues the unique referral link from its authenticated account affiliate area; this chat run has no authenticated Adoric UI session.',reason:'Repository and Gmail duplicate checks are clear and the official program is free, but account registration/referral-link recovery is not complete.',next_action:'Use the official Adoric free-account route with support@coshuma.com, checking for an existing account first. If absent, register once and recover the exact vendor-issued customer referral URL. Stop for CAPTCHA, OTP, legal/program consent, forced identity verification or payment approval.',do_not_reapply:true,verified_at:checkedAt,github_issue:499});}fs.writeFileSync(queuePath,`${JSON.stringify(queue,null,2)}\n`);
const urls=['https://coshuma.com/tool/adoric.html','https://coshuma.com/best/adoric-free-plan-pricing.html','https://coshuma.com/compare/adoric-vs-poptin.html'];const sitemapPath='public/sitemap.xml';let sitemap=fs.readFileSync(sitemapPath,'utf8');for(const url of urls){if(!sitemap.includes(`<loc>${url}</loc>`))sitemap=sitemap.replace('</urlset>',`  <url>\n    <loc>${url}</loc>\n    <changefreq>weekly</changefreq>\n  </url>\n</urlset>`);}fs.writeFileSync(sitemapPath,sitemap);
const llmsPath='public/llms.txt';let llms=fs.readFileSync(llmsPath,'utf8');if(!llms.includes('https://coshuma.com/tool/adoric.html'))llms+='\n## Adoric buyer guides\n\n- https://coshuma.com/tool/adoric.html — Adoric free plan, Shopify trial, onsite conversion features and product-fit buyer guide\n- https://coshuma.com/best/adoric-free-plan-pricing.html — Adoric non-Shopify free plan and Shopify trial/pricing decision guide\n- https://coshuma.com/compare/adoric-vs-poptin.html — Adoric vs Poptin popup and onsite conversion comparison\n';fs.writeFileSync(llmsPath,llms);
const hubBlock=`\n<section data-adoric-fastlane="2026-09-14" class="max-w-6xl mx-auto px-6 pb-10"><div class="rounded-2xl border border-fuchsia-500/25 bg-fuchsia-500/5 p-5"><div class="text-xs uppercase tracking-widest text-fuchsia-300 font-bold">Popups & onsite conversion</div><p class="mt-2 text-sm text-slate-300"><a class="font-bold text-white hover:text-fuchsia-300" href="/best/adoric-free-plan-pricing.html">Adoric free plan & pricing</a> · <a class="font-bold text-white hover:text-fuchsia-300" href="/tool/adoric.html">Adoric buyer guide</a> · <a class="font-bold text-white hover:text-fuchsia-300" href="/compare/adoric-vs-poptin.html">Adoric vs Poptin</a></p></div></section>\n`;
for(const file of ['public/best/index.html','public/compare/index.html','index.html']){if(!fs.existsSync(file))continue;let html=fs.readFileSync(file,'utf8');if(!html.includes('data-adoric-fastlane="2026-09-14"')){html=html.includes('</main>')?html.replace('</main>',`${hubBlock}</main>`):html.replace('</body>',`${hubBlock}</body>`);fs.writeFileSync(file,html);}}
const poptinPath='public/tool/poptin.html';if(fs.existsSync(poptinPath)){let html=fs.readFileSync(poptinPath,'utf8');if(!html.includes('data-adoric-related="2026-09-14"')){const links=`<section data-adoric-related="2026-09-14" class="mx-auto mt-8 max-w-5xl rounded-2xl border border-fuchsia-500/25 bg-fuchsia-500/5 p-6"><h2 class="text-xl font-black text-white">Compare another free-entry popup platform</h2><p class="mt-2 text-sm text-slate-300">Adoric and Poptin both offer no-cost entry for non-Shopify sites, but they meter usage differently: Adoric documents pageviews while Poptin documents visitors. Compare the workflows rather than treating those limits as equivalent.</p><div class="mt-4 flex flex-col gap-2 sm:flex-row"><a href="/compare/adoric-vs-poptin.html" class="rounded-xl bg-fuchsia-600 px-5 py-3 text-center text-sm font-black text-white">Adoric vs Poptin →</a><a href="/tool/adoric.html" class="rounded-xl border border-white/10 px-5 py-3 text-center text-sm font-black text-white">Adoric buyer guide →</a></div></section>`;html=html.includes('</main>')?html.replace('</main>',`${links}</main>`):html.replace('</body>',`${links}</body>`);fs.writeFileSync(poptinPath,html);}}
console.log('Adoric fast-lane state, browser queue and discoverability ensured');
